twobulls/easy-genomics

packages/front-end/src/app/pages/orgs/[orgId]/index.vue
I couldn't avoid side effects of disabling the click through action, so just removing the clickable row until we can address this properly.
=> fix: remove clickable rows for users

.projenrc.ts, README.md, config/easy-genomics.example.yaml, package.json, packages/back-end/src/main.ts, packages/shared-lib/src/app/schema/configuration.ts, packages/shared-lib/src/app/types/configuration.d.ts
This PR updates the `easy-genomics.example.yaml` and README.md files to inc the optional `'seqera-api-base-url' setting in case the AMD training wishes to configure Easy Genomics with a self-hosted NextFlow Tower instance.
It also adds a sanity logic to ensure that a trailing slash for `'seqera-api-base-url' setting is removed.
It also adds the root project convenience script `'build-and-deploy'` to allow both the FE and BE to be deployed in one command once the initial BE and FE have been deployed.
=> fix(EG-653): update config to inc 'seqera-api-base-url' setting & root 'build-and-deploy' convenience script

packages/front-end/src/app/pages/labs/[labId]/index.vue
Fixes the lab role not updating in the UI when changed between "Lab Manager" and "Lab Technician".
=> fix(EG-664): update lab role in UI  on change

packages/front-end/src/infra/constructs/www-hosting-construct.ts
This PR adds the AWS Account ID as a prefix for the S3 Bucket used by the FE www content.
e.g. `{aws-account-id}-{app-domain-name}`
This will help improve the reliability of the FE deployment, especially for testing when the configured `app-domain-name` setting is not a real FQDN.
=> fix(EG-665): improve FE www S3 bucket name uniqueness to improve deployment reliability

.projenrc.ts, package.json
Running `lint-all` from root was causing an issue between ESLint/tsconfig establishing the right folder path/context, throwing an error and preventing the ability to commit. 
The simplest solution was to separate the lint tasks out separately and run sequentially as part of the existing `lint-staged` script. The Prettier step has been moved to run before ESLint also as best practice.
=> fix(EG-668): lint package folders separately to fix context issue

.gitignore, .projenrc.ts, packages/back-end/.gitignore, packages/back-end/LICENSE, packages/front-end/.gitignore, packages/front-end/LICENSE, packages/shared-lib/.gitignore, packages/shared-lib/LICENSE, projenrc/apache-license.ts, projenrc/license-text/Apache-2.0.txt
Extends the Projen License class to apply the Apache-2.0 and override the year and owner placeholders.
=> fix: apply apache license with correct copyright name and year

packages/front-end/src/app/pages/labs/[labId]/index.vue
Changes Pipelines tab to Runs tab as the first/default tab when viewing the Lab.
=> feat(EG-641): change default labs tab to Runs

packages/front-end/src/app/components/EGRunPipelineStepper.vue
Change "Back to Pipelines" button label to "Back to Runs" to more accurately reflect the navigation redirect.
=> feat(EG-586): change "Back to Pipelines" button label to "Back to Runs"

packages/front-end/src/app/pages/labs/[labId]/[workflowId]/index.vue
Small fix to add manifest name underneath run name in the Labs workflow page
=> fix(EG-571): add manifest name underneath run name

packages/front-end/src/app/pages/labs/[labId]/[workflowId]/index.vue, packages/front-end/src/app/pages/labs/[labId]/index.vue
Fixes an issue with the pipeline name (e.g. `nf-core/rnaseq`) breaking when viewing cancelled runs. This is due to the `manifest` property value not existing in the cancelled run data. This same value exists in `workflow.projectName` so the prop value references this value now instead.
Also fixes a console warning for the `labName` null value before the page data is retrieved.
=> fix(EG-571): pipeline name 

packages/shared-lib/src/app/schema/nf-tower/connection-test.ts
Prevents the fields from being empty
=> chore: fields can not be empty

packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue, packages/front-end/src/app/pages/labs/[labId]/index.vue, packages/front-end/src/app/stores/pipeline-run.ts
This PR removes the `transactionId` variable declaration from the 2nd Stepper `EGRunPipelineFormUploadData.vue` and adds it to the initial `lab/[labId]/index.vue page` and stores the transactionId value within the `usePipelineRunStore()` so it can be easily accessed by any Stepper.
This will allow files to be uploaded consistently to the same S3 Bucket Path for the current Launch Run session.
=> feat(EG-638): remove transactionId variable from stepper 2 and add to lab/[labId]/index.vue page usePipelineRunStore()

.projenrc.ts, packages/front-end/package.json
This PR fixes the FE `pnpm run nuxt-dev` command to ensure it runs the `build-front-end` script which will include the shared-lib as part of the build process.
This will allow a clean checkout of this Easy Genomics repo, and run the FE locally using `pnpm run nuxt-dev` with the following sequence of commands:
```
git clone https://github.com/twobulls/easy-genomics.git
cd easy-genomics
pnpm install
// Configure the easy-genomics.yaml file and deploy the BE if not already deployed to AWS
...
cd packages/front-end
pnpm run nuxt-dev
```
=> fix(EG-697): fix local FE build process to ensure shared-lib is included to run nuxt-dev

packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue
Pipeline `params` prop was losing reactivity causing the store object to not update on inputs.
=> fix(EG-701): params reactivity

packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue, packages/front-end/src/app/composables/usePipeline.ts
This PR makes the `input` field editable in the Edit Parameters step, providing flexibility to input an existing s3 bucket URL.
The "Download sample sheet" button has also been moved from Step 3 to Step 2, and will display once the file pairs have been successfully uploaded.
=> feat(EG-700): make s3 url editable input

packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue
- Adds `watchEffect` on props values to fix the `params` store object not updating. 
- Cache the store as a local const for perf improvement.
=> fix(EG-701): pipeline param inputs not updating in store

packages/back-end/src/app/controllers/easy-genomics/organization/list-organizations.lambda.ts, packages/back-end/src/app/utils/auth-utils.ts
This PR modifies the `/easy-genomics/organization/list-organizations` API to return a list of Organizations depending on the Cognito User Session.
If the User is the SystemAdmin it will return all existing Organizations in the Platform.
If the User is a normal User then it will only return a filtered list of Organizations that the User has been invited to.
=> feat(EG-704): update list-organization API for SysAdmin/User filtering

packages/front-end/tests/e2e/EditLab.spec.e2e.ts
Fixes #
- added a timeout code after editing Lab changes to give enough time to save the changes and the toast messages to appear
=> feat(EG-713): added timeout in editlab test

packages/front-end/tests/e2e/GrantAccesstoUserToALab.spec.e2e.ts
Fixes #
This pr includes new scripts for testing granting lab access to a user via the Edit User Access page
There is validation for when user is already added, it will be deleted first via the Lab User tab
=> feat(EG-722): grant access to a lab

packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue, packages/front-end/src/app/components/EGRunPipelineFormRunDetails.vue, packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue, packages/front-end/src/app/components/EGRunPipelineStepper.vue, packages/front-end/src/app/pages/labs/[labId]/[pipelineId]/run-pipeline.vue, packages/front-end/src/app/pages/labs/[labId]/index.vue
This PR fixes:
* S3Urls in the samplesheet for the uploaded files
* Sets the samplesheet S3Url for the `input` property
* Adds some missing imports for FE pages
* Renders the edited settings in Step 3. in the Step 4. summary page (to update to Nick's Figma designs still)
* Filters the Pipeline's sections for any that contain all hidden settings since it is not to be edited/visible in Step 3 and Step 4.
NOTE: There is still a bug with the manual editing of the input samplesheet text field in Step 3. This only gets updated and displayed properly in Step 4 after going back to Step 3, and then Step 4 again. It seems to be a storage update issue.
=> fix(EG-680): minor updates to support NF integration

packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue
Fix to ensure only `.gz` files can be added via drag-and-drop or file input selection to the pipeline uploader.
=> fix(EG-622): prevent uploading of non-gz file types

packages/shared-lib/src/app/types/easy-genomics/sample-data.ts
This PR adds the missing `OrganizationAdmin: true` property to the seeded test user account.
=> fix(EG-751): update test.user@easygenomics.org OrganizationAccess to inc OrganizationAdmin flag

packages/back-end/src/infra/stacks/data-provisioning-nested-stack.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
This PR updates the `data-provisioning-nested-stack.ts` to create a single shared S3 Bucket named `${this.props.env.account!}-${this.props.namePrefix}-lab-bucket` to simulate an existing S3 Bucket for a Lab to select and use.
e.g. `{AWS ACCOUNT ID}-dev-quality-lab-bucket`
It also removes an unnecessary `s3:CreateBucket` IAM policy for the `create-laboratory` API since we are no longer provisioning new S3 Buckets at Lab creation.
=> fix(EG-750): setup shared s3 bucket with cors settings for deployment

packages/back-end/src/app/controllers/easy-genomics/files/request-file-download.lambda.ts, packages/back-end/src/app/services/s3-service.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/shared-lib/src/app/schema/easy-genomics/files/request-file-download.ts, packages/shared-lib/src/app/types/easy-genomics/files/request-file-download.d.ts, packages/shared-lib/src/app/utils/HttpError.ts
This PR adds the POST `/easy-genomics/files/request-file-download` API and it requires the JSON payload:
```
{
"LaboratoryId": "<< Laboratory ID >>",
"Path": "<< File Path / S3 Key >>"
}
```
It returns:
```
{
"DownloadUrl": "<< Pre-Signed S3 URL >>"
}
```
The `DownloadUrl` is set to expire after 60 seconds.
The LaboratoryId is used to:
1. Verify if the User calling the API has access to the Laboratory
2. Retrieve the S3 Bucket for the Laboratory to generate the Pre-signed S3 URL to obtain the file
---
The existing `/easy-genomics/upload/...` APIs should be refactored to sit in the `/easy-genomics/files/...` path for logical grouping. This will need to be done in a separate ticket / PR.
Additionally, the `validateLaboratoryManagerAccess()` and `validateLaboratoryTechnicianAccess()` …
=> feat(EG-758): add request-file-download API

packages/back-end/src/app/controllers/easy-genomics/laboratory/list-laboratories.lambda.ts, packages/back-end/src/app/utils/auth-utils.ts, packages/back-end/test/app/utils/auth-utils.test.ts
Super Admins and Organizational Admins can get a list of all laboratories.
For all other users, they will need Laboratory Access to see the laboratories via the list-laboratories endpoint.
=> feat: restrict laboratories by organizational access

packages/back-end/src/app/controllers/easy-genomics/files/request-file-download.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/list-laboratories.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/read-laboratory.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/update-laboratory.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/user/add-laboratory-user.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/user/edit-laboratory-user.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/user/remove-laboratory-user.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/read-organization.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/update-organization.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/user/add-organization-user.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/user/edit-organization-user.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/user/remove-organization-user.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/user/request-organization-user.lambda.ts
I made a mistake with the user access when adding lab manager restrictions. The validation check should be failing if neither of the requirements are met, not either of them.
=> fix: incorrect operator was used for user access

packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-request.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue, packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue, packages/front-end/src/app/composables/usePipeline.ts, packages/front-end/src/app/stores/pipeline-run.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-sample-sheet.d.ts
This PR makes the following changes in order to fix the NextFlow Launch Run request error:
1. Modify the existing `create-file-upload-request` and `create-file-upload-sample-sheet` APIs to adopt the new S3 Path format: 
`s3://${ Lab's Set S3 Bucket }/${ laboratory.OrganizationId }/${ laboratory.LaboratoryId }/next-flow/${ transactionId }`
2. The `create-file-upload-sample-sheet` API has also been modified to return the s3Bucket, and s3Path in order to reuse these details for the Pipeline's `outdir` and `workDir` parameter settings so that the processing and output files can all be saved in the same S3 transaction location along side the uploaded data files and sample-sheet.
3. The Pipeline Launch Step 3 UI will now set the `input` and `outdir` settings so the results can be saved …
=> fix(EG-729): resolve NextFlow launch Run error

packages/front-end/src/app/components/EGLabDetailsForm.vue, packages/front-end/src/app/components/EGRunPipelineFormRunDetails.vue
- Increases pipeline run name to 50 chars max
- Also makes some mandatory field names consistently styled.
=> feat(EG-762): increase run name char limit

packages/front-end/tests/e2e/EditOrg.spec.e2e.ts
This is to address the timeout issue shown when running the EditOrg script
**EditOrg.spec.e2e.ts > Update an Org Successfully**
Error: Timed out 5000ms waiting for expect(locator).toBeVisible()
Locator: getByText('This is the default Organization back to original').first()
Expected: visible
Received: <element(s) not found>
Call log:
- expect.toBeVisible with timeout 5000ms
- waiting for getByText('This is the default Organization back to original').first()
Error: Timed out 5000ms waiting for expect(locator).toBeVisible()
=> feat(EG-799): add timeout to EditOrg

packages/front-end/src/app/pages/labs/index.vue
Fixes a small regression that caused the "No Labs" messaging to appear before the data is ready.
=> fix(EG-797): logic for empty labs state

packages/front-end/src/app/components/EGOrgView.vue
Adds a single line skeleton loader for the Org description
=> fix(EG-796): add Org description skeleton

README.md, config/easy-genomics.example.yaml, packages/back-end/src/infra/stacks/data-provisioning-nested-stack.ts, packages/back-end/src/main.ts, packages/shared-lib/src/app/schema/configuration.ts, packages/shared-lib/src/app/types/configuration.d.ts, packages/shared-lib/src/app/types/easy-genomics/sample-data.ts, packages/shared-lib/src/infra/types/main-stack.d.ts
This PR updates the BE infra to provision Lab Manager and Lab Technician User accounts based on the optional specified settings in the `easy-genomics.yaml` configuration file:
* `lab-manager-email` / `lab-manager-password`
* `lab-technician-email` / `lab-technician-password`
The aim of this enhancement to allow for automated FE testing to be written to verify Lab Manager and Lab Technician access.
The following is an example of `easy-genomics.yaml` configuration file with the various User Roles declared for provisioning:
```
easy-genomics:
configurations:
- test:
aws-account-id: '...'
aws-region: '...'
env-type: 'dev'
app-domain-name: 'test.dev.easygenomics.org'
aws-hosted-zone-id: '...'
aws-certificate-arn: 'arn:aws:acm:..'
back-end:
jwt-secret-key: '...'
system-admin-email: …
```
=> feat(EG-807): update BE data provisioning to inc lab manager & lab technician accounts

packages/back-end/src/main.ts
This PR fixes a regression from recent enhancements to the BE user data provisioning logic.
The `sysAdminEmail` and `sysAdminPassword` were inadvertently excluded from being passed to the data provisioning stack for processing.
=> fix(EG-814): fix BE main infra stack to pass sysAdminEmail & sysAdminPassword for data provisioning

packages/front-end/src/app/pages/labs/[labId]/index.vue, packages/front-end/src/app/stores/workflow.ts
This PR adds an auto-refresh of the Laboratory Runs data every two minutes. 
Notable changes: 
- some refactoring of `stores/workflow.ts` was needed to remove the empty loading state each time the data refreshes. 
- re-organised the code structure which had gotten a bit unwieldily over time.
=> feat(EG-574): auto-refresh Runs data 

packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
Due to an issue in the pipeline not seeing any test for Org Admin, I've consolidated existing and new tests for an Org Admin including the following:
- 01 - Create a Laboratory Successfully
- 02 - Update a Laboratory Successfully
- 03 - Grant access to a user to a Laboratory via Edit User Access Successfully
- 04 - Remove user from a Laboratory Successfully
**Note:** Please ignore the commented lines, this will be a guide on missing test scripts
=> feat(EG-816): create lab script for an org admin

.gitignore, .projenrc.ts, packages/front-end/package.json, packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
This PR contains few improvement on existing and new test scripts all housed in the 'Organizations_System_Admin'
01 - Remove an Organization Successfully
02 - Create a new Organization Successfully
03 - Invite a user to an Org Successfully
04 - Change a user's Organization Admin access
05 - Remove Invited user to an Org Successfully
06 - Update an Org Successfully
Please note that the succeeding runs will fail due to a dependency on a bug fix for **EG-811**
=> feat(EG-819): set automation org

packages/back-end/src/app/services/easy-genomics/organization-service.ts
This PR fixes the organization-service delete() method to correctly remove the Organization's lower-case name from the DynamoDB unique-reference table.
=> fix(EG-811): update organization-service delete() to correctly remove unique reference

packages/back-end/src/app/controllers/easy-genomics/laboratory/list-laboratories.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/list-organizations.lambda.ts, packages/back-end/src/app/utils/auth-utils.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/back-end/test/app/utils/auth-utils.test.ts, packages/shared-lib/src/app/utils/HttpError.ts
Users who have been given/removed access for Organizations and Laboratories won't have their org access in their ID Token updated to reflect that unless they log out and log back in.
Here we will check on the Org and Lab list endpoints if that org access is current and throw an error to let the FE know to refresh the users ID Token and try again.
=> feat(EG-776): verify current user org access for list endpoints

.projenrc.ts, packages/front-end/package.json
Makes the `test-e2e` command failover so that if any of the test scripts fail the next script will try and execute. 
e.g. Currently tests for Sys Admin run before Org Admin. If any of the Sys Admin tests fail, the entire script exists, preventing Org Admin tests from running.
=> feat(EG-828): make ci/cd test execution failover

packages/back-end/src/app/controllers/easy-genomics/list-buckets.lambda.ts, packages/back-end/src/app/services/s3-service.ts, packages/back-end/src/infra/stacks/data-provisioning-nested-stack.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/front-end/src/infra/constructs/www-hosting-construct.ts
This PR adds S3 Bucket tagging to:
| Bucket | Tags |
|--------|------|
| **FE www hosting bucket** | `'easy-genomics:s3-bucket-type': 'www'` |
| **BE provisioned lab bucket** | `'easy-genomics:s3-bucket-type': 'data'` |
The `list-buckets` API has been enhanced to lookup the S3 Bucket's Tag details and then filter for only the S3 Buckets containing the Tag key/value pair: `'easy-genomics:s3-bucket-type': 'data'`.
This will allow customers to create their own S3 Buckets / use their existing S3 Buckets with Easy Genomics if they belong to the same AWS Region as the Easy Genomics deployment and have added the tag `'easy-genomics:s3-bucket-type': 'data'`.
AWS S3 prevents looking up an S3 Bucket's tags if the Bucket does not belong to the same AWS Region as the caller (i.e. Easy Genomics …
=> feat(EG-770): add s3 bucket tags to enable bucket filtering for list-buckets API

packages/back-end/src/infra/stacks/auth-nested-stack.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
This PR removes the SES IAM restrictions for email identities `'*@twobulls.com'`, and `'*@deptagency.com'` to allow for broader testing, and also enable customers to invite users to their own deployment properly.
=> fix(EG-836): remove SES IAM restrictions on email identities to enable broader end-user testing

packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue, packages/front-end/src/app/composables/usePipeline.ts, packages/front-end/src/app/pages/labs/[labId]/[pipelineId]/run-pipeline.vue, packages/front-end/src/app/plugins/api.ts, packages/front-end/src/app/repository/modules/files.ts, packages/front-end/src/app/stores/workflow.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-sample-sheet.d.ts
This PR updates the `Run Pipeline Step 2` UI's `Download sample sheet` button logic to leverage the `/easy-genomics/file/request-file-download-url` API to retrieve the current samplesheet.csv file store on S3.
This replaces the previous implementation which obtained a copy of the CSV content from the BE API `/easy-genomics/upload/create-file-upload-sample-sheet` API which is only called once after all the files are uploaded.
The use of the `/easy-genomics/file/request-file-download-url` API allows the UI to reliably download the the latest samplesheet.csv file from S3. This will complement the planned `Run Pipeline Step 2` UI's enhancement to allow the end-user to also upload their own samplesheet.csv file to S3.
=> feat(EG-841): download actual samplesheet

packages/back-end/src/app/controllers/easy-genomics/file/request-list-bucket-objects.lambda.ts, packages/back-end/src/app/services/s3-service.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/shared-lib/src/app/schema/easy-genomics/file/request-list-bucket-objects.ts, packages/shared-lib/src/app/types/easy-genomics/file/request-list-bucket-objects.d.ts
This PR adds the `/easy-genomics/file/request-list-bucket-objects` API to help support the new File Manager UI.
It requires the following example JSON payload:
```
{
"LaboratoryId": "bbac4190-0446-4db4-a084-cfdbc8102297",
"S3Bucket": "851725267090-dev-test-lab-bucket",    // Optional
"S3Prefix": "61c86013-74f2-4d30-916a-70b03a97ba14/bbac4190-0446-4db4-a084-cfdbc8102297/next-flow/e80511e9-d9d9-44ce-a18d-7b8c20043bae/",    // Optional
"MaxKeys": 1000    // Optional
}
```
- If the `S3Bucket` is omitted, then it will default to the Lab's configured `S3Bucket`.
- If the `S3Prefix` is omitted, then it will default to the Lab's reserved S3 path comprising of the Lab's `OrganizationId`, and `LaboratoryId` (e.g. `61c86013-74f2-4d30-916a-70b03a97ba14/bbac4190-0446-4db4-a084-cfdbc8102297/`).
=> feat(EG-834): add request-list-bucket-objects api

packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
This new script for System Admin aims to
- check if the All labs tab is empty and display a console message
- check if Org has a lab and if so click on the lab
- check if the Lab has a user
- check if if the user can access the Edit button in the lab details tab
=> feat(EG-792): create sys admin script for labs

packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/shared-lib/src/app/schema/easy-genomics/laboratory-run.ts, packages/shared-lib/src/app/types/base-entity.d.ts, packages/shared-lib/src/app/types/easy-genomics/laboratory-run.d.ts
This PR adds a new DynamoDB `laboratory-run-table` for tracking AWS HealthOmics / Seqera Cloud launched runs for a Laboratory.
The `laboratory-run-table` leverages the following indexes for support easier lookup of records by:
- LaboratoryId // DynamoDB Partition Key (String)
- RunId // DynamoDB Sort Key (String) & Global Secondary Index (String)
- UserId // Global Secondary Index (String)
- OrganizationId // Global Secondary Index (String)
This PR also adds the `laboratory-run` type definition and Zod validation schemas.
=> feat(EG-833): add dynamodb laboratory-run-table

packages/back-end/src/app/controllers/easy-genomics/user/create-user-invitation-request.lambda.ts, packages/back-end/src/app/services/ses-service.ts, packages/back-end/src/infra/constructs/ses-construct.ts
This PR improves the `/easy-genomics/user/create-user-invitation-request` API to properly support:
1. Inviting new a User to the Platform and Organization
2. Re-inviting an existing Invited User to the Platform and Organization (did not complete invitation workflow, and was removed from an invited Organization).
3. Adding an existing Active User to an Organization
The bug that was identified was caused by workflow 2 due to the shared logic.
The logic is now refactored to separate functions for easier understandability and maintenance.
- inviteNewUserToOrganization()
- reinviteExistingUserToOrganization()
- addExistingUserToOrganization()
The SES `ExistingUserInvitationEmailTemplate` template has also been renamed to `ExistingUserCourtesyEmailTemplate` to avoid confusion with the …
=> fix(EG-856): improve create-user-invitation-request API logic

packages/back-end/src/app/controllers/easy-genomics/user/create-user-forgot-password-request.lambda.ts, packages/shared-lib/src/app/utils/HttpError.ts
This PR fixes the `/easy-genomics/user/create-user-forgot-password-request` API so that it always returns a false positive (200 OK response) if it encounters an error from:
* Invalid Forgot Password JWT
* User Account deactivated (Status = `'Inactive'`)
* User Cognito Account deactivated
These errors will continue to be logged in the respective AWS CloudWatch logs for debugging.
But it is important for this API to return a false positive to the FE in order to prevent snooping of User account emails.
=> fix(EG-840): fix create-user-forgot-password-request API error handling

packages/back-end/src/app/controllers/easy-genomics/file/request-file-download-url.lambda.ts
This PR fixes the `/easy-genomics/file/request-file-download-url` API to generate pre-signed download URLs for the specified download file.
The S3 API `getBucketLocation()` call returns null for S3 Bucket's that are located in `us-east-1`. S3 Bucket's located in other S3 regions will return always return their region value.
The fix improves the  locationConstraint checking for `us-east-1`. If the S3 API response was to be modified in the future to return `us-east-1` instead of null, the logic will still work.
=> fix(EG-841): fix request-file-download-url API to handle us-east-1 S3 requests

packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
Fixes adding and removing the `Lab Manager` user. Test was failing due to the `lab manager` input being non unique (found in both the `Lab Manager` user and `Zig Lab Manager` usernames) and was therefore non-selectable as a user. Search input has been changed to the unique email address so as to avoid future conflicts.
=> fix(EG-864): fix Labs Manager E2E test

packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue, packages/front-end/src/app/components/EGRunPipelineStepper.vue, packages/front-end/src/app/stores/ui.ts
This fixes the backtrack-to-steps-upload bug because as soon as you click Launch Workflow Run the tabs will disable.
=> fix(EG-867): lock pipeline run page stepper tabs on click of launch pipeline

packages/front-end/src/app/components/EGFileExplorer.vue, packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/components/EGTable.vue, packages/front-end/src/app/composables/useSort.ts
Fixes include: 
- `Date modified` date column sorting now working as expected
- Page 2 onwards was not returning results if one level deep in the folder structure
- Cleared the Lab API polling on leaving the Lab view page, which would otherwise poll unnecessarily in the background even after navigating away from the page
Some refactoring was done on the `EGTable` component: general regression performed without noticing any impact to other table implementations.
=> fix(EG-830): file explorer fixes + lab polling fix

packages/back-end/src/app/controllers/aws-healthomics/workflow/list-private-workflows.lambda.ts, packages/back-end/src/app/utils/rest-api-utils.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts
This PR adds the `/aws-healthomics/workflow/list-private-workflows?laboratoryId={Laboratory ID}` API to return a list of available Private Workflows from the AWS HealthOmics service in the region of the Easy Genomics deployment.
This API will require a `laboratoryId` query parameter in order to lookup the associated Laboratory in order to verify access it has `AwsHealthOmicsEnabled` (similar to the `/nf-tower/pipeline/list-pipelines?laboratoryId={Laboratory ID}` API).
```
if (!laboratory.AwsHealthOmicsEnabled) {
throw new UnauthorizedAccessError('Laboratory does not have AWS HealthOmics enabled');
}
```
The `/aws-healthomics/workflow/list-private-workflows` API also will support AWS HealthOmics pagination parameters and search filtering by name:
* …
=> feat(EG-870): add '/aws-healthomics/workflow/list-private-workflows' API

packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
Adds the correct role to allow lab deletion to queue up the lab run deletes
=> fix: add run roles to lab delete api

packages/back-end/src/app/controllers/aws-healthomics/run/list-runs.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/workflow/list-private-workflows.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/workflow/run/list-private-workflow-runs.lambda.ts, packages/back-end/src/app/utils/rest-api-utils.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts
This PR adds the `/aws-healthomics/run/list-runs` API endpoint.
It requires the query parameter `?laboratoryId={LaboratoryId}` to verify if the Lab has AWS HealthOmics access enabled.
It also supports the following optional query parameters:
- `maxResults`: pagination limit
- `nextToken`: pagination offset index
- `name`: search filtering by run name
- `status`: search filtering by run status 
Note: the  `/aws-healthomics/workflow/list-private-workflows` API does not support the status query parameter so it is explicitly removed to avoid SDK request type errors.
=> feat(EG-872): add '/aws-healthomics/run/list-runs' API endpoint

packages/back-end/src/app/controllers/aws-healthomics/run/read-run.lambda.ts, packages/back-end/src/app/services/omics-service.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts
This PR adds the HTTP GET `/aws-healthomics/run/read-run/{RunId}?laboratoryId={LaboratoryId}` API endpoint.
It requires:
- `RunId` path parameter
- `LaboratoryId` query parameter
This API basically returns the Run's result details for an AWS HealthOmics Workflow.
=> feat(EG-878): add '/aws-healthomics/run/read-run' API endpoint

packages/back-end/src/app/controllers/aws-healthomics/run/cancel-run.lambda.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts
This PR adds the HTTP PUT `/aws-healthomics/run/cancel-run/:{RunId}?laboratoryId={LaboratoryId}` API to cancel an existing Workflow Run.
It requires:
* `RunId` path parameter
* `LaboratoryId` query parameter
=> feat(EG-877): add '/aws-healthomics/run/cancel-run' API

packages/front-end/src/app/components/EGHeader.vue, packages/front-end/src/app/components/EGInitialsCircle.vue, packages/front-end/src/app/composables/useAuth.ts, packages/front-end/src/app/composables/useUser.ts, packages/front-end/src/app/layouts/default.vue, packages/front-end/src/app/repository/factory.ts, packages/front-end/src/app/stores/user.ts
Fix org dropdown not working for superuser
I forgot to build the org switcher dropdown for superuser and it didn't work. In this PR I fixed this.
Also in this PR, I made some refactoring changes to the logic that pulls out user data from the token and saves it into the user store. My goal was to unify the code flows (have fewer functions doing roughly the same thing) and make it consistent and automatic, so that we can reference the data in the user store without needing to think about the state of the application.
I also moved some of the display logic (re: current user display name and initials) to getters in the user store.
e2e tests passed in build2.
Should be no change to user space or development from refactors.
Dropdown now works for superuser.
=> fix(EG-868): org dropdown not working for superuser

packages/back-end/src/app/controllers/aws-healthomics/workflow/read-private-workflow.lambda.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts, packages/shared-lib/src/app/utils/HttpError.ts
AWS Omics get workflow api
This new endpoint takes in a workflowId (as `id`) in the path and a laboratoryId as a query param. The laboratory is used for checking if the laboratory has access to AWS Omics, and also for user permissions. This is only for private workflows.
You will need to have a private workflow already setup in AWS Omics. You can use the _list-private-workflows_ endpoint to list out existing private workflows, then use the id's with this endpoint. If there are no private workflows you will need to create one in AWS, either through the console or the command line.
No other changes or impacts to the project outside of added functionality
Laboratories at present can't be enabled for AWS Omics via the FE, this may change in the future but I had to manually enable this via …
=> feat(EG-874): omics get workflow api

packages/back-end/src/app/controllers/aws-healthomics/run/cancel-run.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/run/list-runs.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/run/read-run.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/workflow/list-private-workflows.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/workflow/read-private-workflow.lambda.ts, packages/back-end/src/app/controllers/nf-tower/compute-env/list-compute-envs.lambda.ts, packages/back-end/src/app/controllers/nf-tower/compute-env/read-compute-env.lambda.ts, packages/back-end/src/app/controllers/nf-tower/file/request-file-download.lambda.ts, packages/back-end/src/app/controllers/nf-tower/pipeline/list-pipelines.lambda.ts, packages/back-end/src/app/controllers/nf-tower/pipeline/read-pipeline-launch-details.lambda.ts, packages/back-end/src/app/controllers/nf-tower/pipeline/read-pipeline-schema.lambda.ts, packages/back-end/src/app/controllers/nf-tower/pipeline/read-pipeline.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/cancel-workflow-execution.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/create-workflow-execution.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/list-workflows.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/read-workflow-metrics.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/read-workflow-progress.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/read-workflow-reports.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/read-workflow.lambda.ts, packages/shared-lib/src/app/constants/errorMessages.ts, packages/shared-lib/src/app/types/easy-genomics/errors.ts, packages/shared-lib/src/app/utils/HttpError.ts
Throw discrete error messages for when a laboratory lacks NextFlow Tower of AWS HealthOmics access
Throw error (EG-315) for AWS HealthOmics endpoints for laboratories that are not allowed to use AWS HealthOmics.
Throw error (EG-316) for NextFlow Tower endpoints for laboratories that are not allowed to use NextFlow Tower.
Labs can be enabled/disabled for both HealthOmics and NextFlow, but UI will likely prevent any actions, so will likely need to use postman to call the API endpoints directly.
Nextflow endpoints are now locked down to only labs enabled for nextflow.
AWS HealthOmics endpoints already had these protections, but just threw a standard not authorized error, where as now they throw a specific error.
=> feat: error for labs missing access to nextflow or omics

packages/back-end/src/app/controllers/nf-tower/workflow/create-workflow-execution.lambda.ts, packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue
Store FE transactionId as LaboratoryRun runId
Update FE Stepper to specify the `transactionId` for the Seqera Pipeline Launch Run `id` so it can be passed from the FE to the BE `/nf-tower/workflow/create-workflow-execution` API, which then can use the supplied `id` to store in the LaboratoryRun record's `runId`.
The same `transactionId` used in the S3 Path where files are uploaded to / output written to should be stored in the LaboratoryRun table's runId field.
=> fix(EG-888): store FE transactionId as LaboratoryRun runId

packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/composables/useFileDownload.ts, packages/front-end/src/app/pages/labs/[labId]/omics-run/[omicsRunId].vue, packages/front-end/src/app/repository/modules/file.ts, packages/front-end/src/app/repository/modules/seqera-runs.ts
Combine Seqera and Omics runs into the one table
Basically, I created a new type `GenericRun` which contains the traits that are needed for handling runs, and convert `SeqeraRun`s and `OmicsRun`s into `GenericRun`s. Several paths that were previously handled separately for Seqera/Omics runs are now converged into one for `GenericRun`s.
e2e tests passed
Known issues:
- Omics runs don't display Owner because it's not provided to us
- Omics runs don't have a subtitle like Seqera runs' projectName subtitle
=> feat(EG-873): combined runs table

packages/back-end/src/app/controllers/easy-genomics/laboratory/create-laboratory.lambda.ts
Fix `NextFlowIntegrationEnabled = false` being overwritten to `true` on lab creation
When creating a lab, if `NextFlowIntegrationEnabled` was `false`, it was being changed to `true`.
The source of this error is this line:
```
NextFlowTowerEnabled: request.NextFlowTowerEnabled || organization.NextFlowTowerEnabled || false,
```
The logical intent of this line is "use `request` value if present, else use `organization` value, else `false`". 
However, the logical OR `||` uses the value on the right if the value on the left is `false`, causing the `organization` value to be used when the `request` value is `false`. (This will have also been happening to `AwsOmicsIntegrationEnabled`, but apparently the `organization` value for that was also `false`, so the behaviour was as expected.) 
The right …
=> fix(EG-885): replace || with ?? to prevent present false value from defaulting to fallback value

packages/back-end/src/app/controllers/aws-healthomics/run/cancel-run-execution.lambda.ts, packages/back-end/src/app/controllers/aws-healthomics/run/create-run-execution.lambda.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts, packages/shared-lib/src/app/schema/aws-healthomics/aws-healthomics-api.ts, packages/shared-lib/src/app/types/aws-healthomics/aws-healthomics-api.ts
Add AWS HealthOmics create-run-execution API
- The existing HTTP PUT `/aws-healthomics/run/cancel-run` API was refactored to `/aws-healthomics/run/cancel-run-execution` for naming consistency.
- Added the HTTP POST `/aws-healthomics/run/create-run-execution` API and IAM policies to enable it to issue startRun commands to AWS HealthOmics.
Refer to the JIRA ticket for the QA acceptance criteria.
None
None
- [ X Code has been commented in particularly hard-to-understand areas.
=> feat(EG-875): add AWS HealthOmics create-run-execution API

packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
Fix the failing sys-admin e2e test due to change of user list format
Removes the exact match requirement from the user email field, because after the user display component consolidation it now also shows the user name
e2e tests pass now
=> fix: sys-admin invite user test failing due to change of user list format

packages/back-end/src/app/controllers/easy-genomics/laboratory/run/create-laboratory-run.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/run/update-laboratory-run.lambda.ts, packages/shared-lib/src/app/schema/easy-genomics/laboratory-run.ts, packages/shared-lib/src/app/types/easy-genomics/laboratory-run.d.ts
Update the LaboratoryRun type def & zod schema properties to properly support create, read, and update LaboratoryRun records.
- Update LaboratoryRun type def & zod schemas to add missing ExternalRunId property to store the Id generated by launching a Seqera Pipeline Run / AWS HealthOmics Workflow Run.
- Simplify the LaboratoryRun's Settings property to a string that will store a stringified JSON object.
- Simplify the HTTP POST `/easy-genomics/laboratory/run/create-laboratory-run` API implementation
- Simplify the HTTP PUT `/easy-genomics/laboratory/run/update-laboratory-run/{:id}` API implementation
- Removed unused LaboratoryRun Read and Delete Zod Schemas
See JIRA ticket for testing instructions.
The improvements in this PR will enable the FE Stepper changes in EG-888 to correctly …
=> fix(EG-897): improve LaboratoryRun type def & zod schema properties

packages/back-end/src/app/controllers/easy-genomics/laboratory/run/update-laboratory-run.lambda.ts
Fix `/easy-genomics/laboratory/run/update-laboratory-run` API to allow updating without Settings property defined.
Fix `/easy-genomics/laboratory/run/update-laboratory-run` API to allow updating without Settings property defined.
None.
None.
=> fix(EG-897): fix update-laboratory-run API when Settings is omitted

packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/pages/labs/[labId]/seqera-run/[seqeraRunId].vue, packages/front-end/src/app/stores/index.ts, packages/front-end/src/app/stores/lab-runs.ts
Add a laboratory runs cache store which enables the run pages to be independent of the lab page
- Add a laboratory run store
- Move seqeraRunId -> labRunId lookup logic from Lab (Run List) page to Run page to reduce coupling and enable direct loading of Run page without previous visit of Lab page
=> refactor(EG-888): laboratory run store

packages/back-end/src/app/controllers/easy-genomics/laboratory/run/process-update-laboratory-run.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/run/update-laboratory-run.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/create-workflow-execution.lambda.ts, packages/back-end/src/app/controllers/nf-tower/workflow/process-workflow-status-check.lambda.ts, packages/back-end/src/app/utils/rest-api-utils.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/back-end/src/infra/stacks/nf-tower-nested-stack.ts
Update nf tower workflow run statuses via a delayed queue
After a NF Tower run is started, check the status of that run and update the laboratory run entry for that run every 5 minutes until the status is `Failed`, `Succeeded` or `Cancelled`. 
After creating a workflow run on NF Tower, there will be a laboratory run entry created for that run (the `ExternalRunId` value will match the workflowId return by NF Tower when starting the run). The status of that laboratory run will be `Pending` initially, but will be updated after 5 minutes to the status of the run in NF Tower. This may currently only be visible via the api in postman.
We are now checking these statuses every 5 minutes for incomplete runs. For the expected loads in a production environment we do not expect to push any limits …
=> feat: update laboratory run status for nf tower workflow runs

packages/back-end/src/app/controllers/aws-healthomics/workflow/list-shared-workflows.lambda.ts, packages/back-end/src/app/services/omics-service.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts
Add HTTP GET `'/aws-healthomics/workflow/list-shared-workflows'` API endpoint.
This PR adds a new API endpoint to retrieve a list of available shared Workflows from 'OTHER' parties.
It is better to have a separate API endpoint to return the list of shared Workflows instead of modifying the existing `'/aws-healthomics/workflow/list-private-workflows'` API endpoint as it would make it harder to maintain into the future since the data responses is different, and the existing pagination/filtering querying behaviour would be compromised.
Refer to JIRA ticket for the testing acceptance criteria.
If shared Workflows is a required functionality that Easy Genomics needs to support, then this API will be ready to meet this requirement, and will require the FE to be enhanced to incorporate this …
=> feat(EG-905): add HTTP GET '/aws-healthomics/workflow/list-shared-workflows' API

packages/front-end/src/app/components/EGButton.vue, packages/front-end/src/app/components/EGDialog.vue, packages/front-end/src/app/components/EGHeader.vue
Add an artificial delay on org switch to make it feel better
Adds new features to EGButton (loading control) and EGDialog (artificial delay).
Then adds a 2 second delay to org switching.
https://github.com/user-attachments/assets/bbcd42e6-a9af-4cd5-98fd-72af877700db
Manually tested feature change, and tested that existing EGDialogs with no artificial delay behave as before.
=> feat(EG-908): switch org delay

packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
The script to remove a user via Edit User Access has been failing consistently so I have added some checks.
The change only affects the Lab_Org_Admin.spec.e2e.ts
The following specific scripts were updated to include checking if the page encounters a loading issue:
05 - Grant access to a user to a Lab via Edit User Access Successfully
06 - Remove user from a Lab via Edit User Access Successfully
The scripts ran several times and passed.
The change only affects the Lab_Org_Admin.spec.e2e.ts
Please note that an intermittent/frequent issue occurs when an Org Admin views the Labs within the Edit User Access. The message appears "There are no labs in your Organization" despite the user/org having existing labs.
=> fix(EG-906): fix org admin remove user

packages/front-end/src/app/components/EGLabView.vue
Fix lab view selected tab breaking after updating lab details to add/remove a compute integration
When editing a lab to add/remove a compute integration, the list of tabs on the page gets changed. The tab index remained the same and there were visual bugs.
This patch makes the page recalculate the right tab index after lab details are updated.
Manual testing
=> fix(EG-901): lab selected tab breaking after details update changes list of tabs

packages/front-end/src/app/components/EGFileExplorer.vue, packages/front-end/src/app/pages/labs/[labId]/seqera-run/[seqeraRunId].vue
Fix console error when run has no S3 contents
When S3 content fetch for a Seqera Run's results returned nothing, a console error would appear alerting to an `(undefined).forEach(...)`.
Adding null conditional operators to skip the `forEach` action avoids the error, and the S3 results widget simply reports "No files or folders found".
Manual before and after testing to confirm this was the cause and solution to this particular error.
=> fix(EG-911): undefined forEach error when no seqera run s3 contents available

packages/front-end/src/app/components/EGFormLabDetails.vue
Prevent autocomplete on personal access token input field
Browsers (at least chrome and firefox) are ignoring the "off" autocomplete when creating a new lab and autofilling in the username and password into the personal access token and workspace id fields. This change sets the autocomplete to "new-password" which the bowsers seem to accept and not autofill with details.
Can be tested by creating a new lab
Removes the annoyance of browsers autofilling fields that are not usernames and passwords
=> fix(EG-890): prevent autocomplete on personal access token input

packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue
Fix frontend not sending through workflow name in run launch request
Just a forgotten `.value` on a `computed`.
WorkflowName will start coming through on run start requests.
=> fix: frontend not sending through workflow name in run launch request

packages/back-end/src/infra/constructs/iam-construct.ts, packages/back-end/src/infra/stacks/aws-healthomics-nested-stack.ts, packages/shared-lib/src/app/schema/aws-healthomics/aws-healthomics-api.ts
fix(EG-899): aws-healthomics iam policy enhancements
Refactor the aws-healthomics-nested-stack IAM policy definitions support running AWS HealthOmics Workflows and improve understandability / maintainability.
Also corrected the CreateRunRequestSchema definition to make `requestId` an optional property as per the SDK definition. It was originally planned to set the EasyGenomics transactionId / runId value for this property for it to be used by AWS HealthOmics instead of generating a new random ID. But the AWS HealthOmics SDK does not return this value in its responses, so this Easy Genomics cannot leverage this property.
None.
None.
=> fix(EG-899): aws-healthomics iam policy enhancements

.projenrc.ts, packages/back-end/src/app/controllers/auth/process-pre-token-generation.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/user/update-user-default-organization-request.lambda.ts, packages/back-end/src/app/services/easy-genomics/platform-user-service.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/shared-lib/src/app/schema/easy-genomics/user.ts, packages/shared-lib/src/app/types/easy-genomics/sample-data.ts, packages/shared-lib/src/app/types/easy-genomics/user.d.ts, projenrc/apache-license.ts, projenrc/easy-genomics-project-setup.ts, projenrc/project-folders-structure.ts
Add support for a User to set their `DefaultOrganization` to allow for more consistency when logging into the platform when they have multiple Organization access.
This PR adds the HTTP PUT `/easy-genomics/user/update-user-default-organization-request/{UserId}` API to allow the current User to update their `DefaultOrganization` property in the DynamoDB `user` table with the JSON payload:
```
{
"DefaultOrganization": "<Organization ID the User already has access to>"
}
```
The `DefaultOrganization` is returned in the JWT upon succestsful authentication against Cognito, so this is available for the FE to detect the User's chosen `DefaultOrganization` for their session (if they have not logged in / switched to an Organization before).
The logic in the `platform-user-service` has also been …
=> feat(EG-923): add User DefaultOrganization setting support

packages/front-end/src/app/components/EGFileExplorer.vue
Fixes Seqera S3 file downloads in nested folders.
S3 directory structure was not being computed correctly at time of download, meaning the download path would always point back to the root folder. This also meant files inside nested directories could not be downloaded.
Manually tested successfully downloading files several levels deep in the folder structure, including duplicate named files.
=> fix(EG-909): generate correct paths for Seqera S3 downloads

packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/front-end/src/app/components/EGFileExplorer.vue, packages/front-end/src/app/pages/labs/[labId]/run/[labRunId].vue, packages/front-end/src/app/stores/lab-runs.ts
Fix LabRun File Manager downloads
There were two main errors causing errors with LaboratoryRun file downloads.
1. The IAM permissions for listing s3 buckets was incorrect
- This required a minor correction
2. The EGFileExplorer (aka File Manager) implementation was still referencing the Seqera List Runs API store and `workDir` to generate the S3 Path for file downloads.
- The File Manager implementation was simplified to use the LaboratoryRun's `InputS3Url` to obtain the S3Bucket and S3Prefix information to then generate the S3ObjectPath for the presigned S3 file download request.
- With the `InputS3Url` information it also allows the File Manager to immediately display the S3 contents within the LaboratoryRun's `transactionId` S3 path. …
=> fix(EG-889): fix LabRun File Manager downloads

packages/front-end/src/app/components/EGHeader.vue
Add the lab name to the header on pages that are specific to a lab. Also add a couple details I missed re: org switcher.
Outside a specific lab: org name only
Inside a lab-specific page: org name and lab name
Features that I missed before about the org switcher:
- Truncate orgs with long names
- Purple help text
=> feat(EG-932): lab name in header

packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
Correct role permissions with lab run updates for omics runs
The lab run update simply had the wrong role permissions.
Creating an omics run should now have it's status eventually update
Was preventing the status of omics runs from progressing
=> fix: give correct permissions for lab update to read omics runs

packages/back-end/src/app/services/easy-genomics/platform-user-service.ts, packages/front-end/src/app/components/EGHeader.vue, packages/front-end/src/app/components/EGOrgView.vue, packages/front-end/src/app/pages/orgs/[orgId]/edit-user/[userId].vue, packages/front-end/src/app/pages/orgs/[orgId]/index.vue, packages/front-end/src/app/pages/orgs/index.vue, packages/front-end/src/app/stores/user.ts
Fix org admin permissions not allowing some org-level user management functions
Org admins couldn't remove users from orgs previously, plus weren't able to view org pages in some circumstances. These are fixed now.
e2e tests full pass ✅ 
Demonstration:
https://github.com/user-attachments/assets/9daca1a7-64a4-44fd-abed-fb5af721aa62
=> fix(EG-954): remove org user not working for org admin

packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/back-end/src/infra/stacks/nf-tower-nested-stack.ts
Suppress cdk nag for NF Tower Access Token wildcard permissions
These wildcard permissions are required so that our lambdas can read the appropriate access token for each laboratory
NA
Simply suppresses the nag, no change in functionality
=> chore: suppress nag for required wildcard permission for access token

packages/front-end/src/app/components/EGStatusChip.vue
Set the default style for run status pills to the basic grey background
Previously, unexpected values for the status pill rendered no pill style. There was code to have a basic grey background as default but it wasn't working. This PR fixes it.
Visually inspected ✅
=> fix(EG-976): grey default style for status pill

packages/front-end/src/app/pages/accept-invitation.vue
On sign up from expired/already accepted invite link; replace non-specific error message with specific error message
Replaces "Something went wrong" message with "Your invite link has been accepted or expired".
Manually tested, e2e tests do not cover this
=> fix(EG-974): replace non-specific error message on expired invite accept with specific error

packages/front-end/src/app/app.vue, packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGS3SampleSheetBar.vue, packages/front-end/src/app/components/EGText.vue
S3 Sample Sheet URL bar + copy URL to system clipboard.
After a successful file upload the S3 sample sheet URL is displayed in both Step 2 and 3 of the stepper with the added ability to copy the URL to the system clipboard.
Also made some font weight tweaks to the `EGText` component so as to be consistent with the Figma UI component guide.
Manually tested on deployed environment.
=> feat(EG-760): s3 sample sheet url bar + copy to clipboard

packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGRunWorkflowFormEditParameters.vue
Allow bypassing file upload 
Changes include:
- File upload "Next Step" button changed to "Save & Continue" if files uploaded and "Skip" if not. Enabled in the Skip case, where was previously disabled.
- Generated `input` and `outdir` parameters now don't generate if S3 bucket/path info (obtained from successful file upload) aren't present
I've tested both pipelines and workflows with and without uploading files and it behaves as expected. 
As the app could previously make the assumption that, post file upload step, there would be files uploaded, and this PR invalidates that assumption, there may be unanticipated effects, such as errors introduced in other parts of the run pipeline/workflow flow that relied on information from the file upload. We'll need to keep an eye out for these.
=> feat(EG-708): skip file upload

packages/front-end/src/app/composables/useFileDownload.ts
Remove `getSignedCsvContent` export from recently deleted function to prevent app from crashing when viewing a lab run.
Manually tested viewing a submitted run.
=> fix(EG-982): view lab run

packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGRunPipelineStepper.vue, packages/front-end/src/app/components/EGRunWorkflowFormEditParameters.vue, packages/front-end/src/app/components/EGRunWorkflowStepper.vue, packages/front-end/src/app/pages/labs/[labId]/run-workflow/[workflowId].vue, packages/front-end/src/app/stores/run.ts
Implement persistent file uploads, and some related fixes/refactors
Features
- File upload persistence - file upload information for a wip run is now stored/read/written directly from the wip run data, so no state is lost when switching between steps
Fixes
- if Omics `/run-workflow/...` route is reached without an omicsTempId in query param, it will generate one automatically
- a console error log when sample sheet wasn't present
- hide sample sheet bar when info isn't present yet
- input/outdir params are generated on file upload success
Refactors
- wip run update functions merge params instead of overwriting `params` object
Dev tested - seems solid as far as I can tell, but any undetected problems should shake out
=> feat(EG-711): persistent file uploads

packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGS3SampleSheetBar.vue
Adds ability to remove a single file if failed during upload.
**Key improvements**
- Prevents invalid operations
- Provides clear UI feedback
- Maintains data integrity
- Handles errors consistently
**UI elements during upload**
- Sample Sheet URL bar:
- Disabled during uploads before renewed sample sheet is available
- Returns to normal state after upload completes
- Retry button:
- Properly enables when file is in error state
- Checks for paired file existence
- Validates network connectivity
**Remove buttons**
- Disabled during active uploads
- Maintains existing offline-state handling
- Disabled in two scenarios:
1. When there's no internet connection
2. During active file uploads
**Overall state management**
- Better handling of file pair states
- Improved validation during the …
=> feat(EG-931): remove single file if failed upload

packages/front-end/src/app/app.vue, packages/front-end/src/app/assets/icons/spinner.svg, packages/front-end/src/app/components/EGDialog.vue, packages/front-end/src/app/components/EGLoadingSpinner.vue, packages/front-end/src/app/components/EGModal.vue, packages/front-end/src/app/components/EGOfflineModal.vue, packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/pages/labs/[labId]/run-workflow/[workflowId].vue
Adds a global "network offline" modal to help prevent interactivity with the app.
Implements a global network connectivity monitor with an automated modal dialog that appears when users lose internet connection. Key changes:
- Added non-dismissible modal that activates automatically on network loss
- Utilizes vueUse's `isOnline` reactive property to detect network state changes
- Prevents user interactions during offline state to avoid API call failures
- Standardized modal styling to match Figma designs and existing modal components
- Refactored loading spinner component to support multiple theme variants
The network status feature provides a more robust error prevention system while maintaining consistent UI/UX patterns across the application.
Network state was tested via both Chrome's …
=> feat(EG-986): add network offline modal

packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/shared-lib/src/app/schema/easy-genomics/upload/s3-file-upload-sample-sheet.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-sample-sheet.d.ts
This PR updates the `/easy-genomics/upload/create-file-upload-sample-sheet` API to support single-read and paired-read sequenced files to generate the sample-sheet CSV file.
It also adds data validation and improved error messaging for the FE to handle as necessary.
This API will now handle requests that define:
- one or more single R1 files
- one or more paired R1 and R2 files
All other scenarios will return an InvalidRequest (HTTP 400) error with the appropriate message.
The sample-sheet generation also checks if the R1 / R2 file starts with the supplied `SampleId` value, and if it doesn't it will also return an InvalidRequest (HTTP 400) error.
The API's response has also been enhanced to include the `SampleSheetType` property that will either have: a `single-read` or a `paired-read` …
=> feat(EG-1004): update the create-file-upload-sample-sheet API to support single read files

packages/back-end/src/app/controllers/nf-tower/workflow/create-workflow-execution.lambda.ts, packages/back-end/src/app/utils/rest-api-utils.ts, packages/front-end/src/app/components/EGRunPipelineFormReview.vue, packages/shared-lib/src/app/utils/HttpError.ts
Fix Seqera Pipeline launching regression.
This PR removes any `paramsText` properties that references variables `${...}` in order to get Seqera Pipelines to launch properly. Without this sanitization the Seqera Launch API will return the error message:
```
{
"message": "Invalid ParamsText - Overwritten parameters cannot contain referenced values"
}
```
It also improves the handling of the returned error message to aid debugging and error display in the FE.
Perform Seqera Pipeline launch from Easy Genomics and it should be successful.
Fixes launching Seqera Pipelines.
None
=> fix(EG-996): fix Seqera Pipeline launch regression

packages/front-end/src/app/components/EGHeader.vue
Remove org and lab names from page header
Now that we have the breadcrumbs showing current org and lab, it's no longer necessary to display them in the page header.
=> feat(EG-1022): remove org and lab names from page header

packages/front-end/src/app/components/EGRunFormUploadData.vue
Fix file upload icon alignment and re-enable cancel upload button
Makes the alignment of all the icons on uploaded files consistent.
Also stumbled upon the cancel upload button that wasn't rendering and fixed that.
The only functional change is bringing back the cancel upload button. I tested it and it works.
=> fix(EG-1006): file upload icon alignment

packages/front-end/src/app/components/EGToast.vue
Fix regression stopping green toasts from getting dismissed by clicking anywhere
I broke the green toast dismiss by click anywhere when I implemented the breadcrumbs because the invisible overlay wrapper from the toasts was blocking the breadcrumbs so I disabled the pointer events but that also disabled the green toast hitbox and this fixes that
=> fix(EG-929): regression stopping green toasts from getting dismissed by clicking anywhere

packages/front-end/src/app/pages/labs/index.vue
Removes the redundant extra create lab button at the top right
=> fix(EG-851): no labs screen showing two create a lab buttons

packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue, packages/front-end/src/app/components/EGRunWorkflowFormEditParameters.vue, packages/front-end/src/app/pages/labs/[labId]/run-pipeline/[pipelineId].vue, packages/front-end/src/app/pages/labs/[labId]/run-workflow/[workflowId].vue, packages/front-end/src/app/stores/run.ts
Update Step 3 UI to display & validate required parameters for Seqera Pipelines and AWS HealthOmics Workflows
This PR adds the display of `*` along side the name of required parameters for Seqera Pipelines and AWS HealthOmics Workflows, and adds validation logic to check the required parameters are not empty. If there are empty required parameters it will display an error dialog message indicating which need to be updated.
This PR has been updated to also fix some existing bugs with the Seqera Pipeline Step 3 form behaviour:
* Updating the `input` field no longer changes the generated sample-sheet url value.
* Pass through the updated values to Step 4, and retain the updated values if switching back to Step 3.
Test launching a Seqera Pipeline or AWS HealthOmics Workflow using the Easy …
=> feat(EG-978): update Step 3 UI to display & validate required parameters

packages/front-end/src/app/components/EGButton.vue, packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGS3SampleSheetBar.vue
Add loading state to URL bar until sample sheet URL has been generated. 
UX behaviour now displays a loading state in the URL bar when uploaded files are in a `success` state and keeps the "Next" button in a disabled state. One the URL becomes available both these boolean states turn `true` and the user can proceed to Step 3.
Manually tested by throttling network requests and simulating behaviour in browser.
Also contains a small improvement to the primary button hover to smooth out hover transition.
=> feat(EG-703): add url bar loading state 

packages/front-end/src/app/components/EGRunPipelineStepper.vue, packages/front-end/src/app/components/EGRunWorkflowStepper.vue
Fix the issue with the run workflow/pipeline stepper highlighting the wrong tab during steps 3 and 4
The issue, as far as I can tell, is caused by UTabs misbehaving. This patch controls the styling manually, but it's not a permanent solution.
=> fix: control run stepper tab styling manually and simplify tab switching

packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGS3SampleSheetBar.vue
Regression - re-enables Skip button in Stepper step 2
Manually verified Skip button is enabled when there are no files, or when files in queue or uploaded are removed.
=> fix(EG-703): enable skip button

packages/front-end/src/app/pages/labs/[labId]/run-pipeline/[pipelineId].vue, packages/front-end/src/app/pages/labs/[labId]/run-workflow/[workflowId].vue
Fix the confirm cancel run modal popup triggering on signout from run stepper pages
If the navigation to path starts with `/signin` it will go ahead without confirmation
=> fix(EG-991): signing out from run stepper triggering confirm cancel modal

packages/front-end/src/app/components/EGRunPipelineFormReview.vue
A Seqera pipeline's hidden fields were not shown on the input step, but were shown on the review step; now they are not
See title
I tested on the Seqera pipeline `k-florek_workshop-build2`, which has the hidden field `email`. It initially appeared in the review step. After this fix it was not rendered.
=> fix(EG-844): hide hidden params from run pipeline step 4

packages/front-end/src/app/components/EGUserAccess.vue
Allow toggling org admin on invited users
This is needed so that the superuser setting up a new org can set the first user(s) to org admins straight away, before the invitations are accepted
I toggled admin on an invited user and it seemed to work fine
This change is intended for the superuser but applies to any user that can toggle org admin.
It mutates user records for users that are on status = INVITED, which we don't normally do.
=> fix(EG-1032): allow toggling org admin on invited users

packages/back-end/src/app/controllers/easy-genomics/user/confirm-user-invitation-request.lambda.ts, packages/back-end/src/app/services/easy-genomics/platform-user-service.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
Fix user invitation to multiple organization activation workflow
This PR fixes the user invitation to multiple organization activation workflow to update all `Invited` OrganizationUser mapping records to `Active`, and also update the User's `OrganizationAccess` metadata, which is used to assist user access and switching.
The existing `PlatformUserService` -> `editExistingUserAccessToOrganization(existingUser: User, organizationUser: OrganizationUser)` method is unmodified as it is used to service individual User / OrganizationUser updating.
A new `PlatformUserService` -> `editExistingUserAccessToOrganizations(existingUser: User, organizationUsers: OrganizationUser[])` method was added to efficiently process multiple OrganizationUser invitation activations using the DynamoDB transaction …
=> fix(EG-981): fix user multi-org activation

packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/shared-lib/src/app/schema/easy-genomics/upload/s3-file-upload-sample-sheet.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-sample-sheet.d.ts
Fix same pair R1 / R2 filename error & improve sample-sheet generation performance
This PR enhances the `/easy-genomics/upload/create-file-upload-sample0sheet` API to:
- handle the edge-case error scenario when the R1 and R2 pair files are uploaded with same filename
- NOTE: this is only possible via Postman API testing
- improve the performance of this API by making the S3 validation file checking optional through the specification of a query parameter `?validate=true`.
Refer to associated JIRA ticket for testing instructions.
None.
None.
=> fix(EG-1021): fix same pair R1 / R2 filename error & improve sample-sheet generation performance

packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-request.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/shared-lib/src/app/schema/easy-genomics/upload/s3-file-upload-manifest.ts, packages/shared-lib/src/app/schema/easy-genomics/upload/s3-file-upload-sample-sheet.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-manifest.d.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-sample-sheet.d.ts
Separate s3 path for aws-healthomics and seqera-platform files
This PR updates the S3 paths for file uploads and sample-sheets to replace the hard-coded `'next-flow'` value with the respective `aws-healthomics` or `seqera-platform` value instead.
Perform Seqera Pipeline / AWS HealthOmics Workflow launches, and the S3 Url will include `aws-healthomics` or `seqera-platform` instead of `next-flow`.
This will appear in the Lab Run's S3InputUrl, S3OutputUrl, and the samplesheet contents too for R1 / R2 paths to the uploaded Fastq files.
None.
None.
=> feat(EG-1005): separate s3 path for aws-healthomics and seqera-platform files

packages/front-end/src/app/components/EGBreadcrumbLabs.vue, packages/front-end/src/app/components/EGBreadcrumbOrgs.vue
Fix text alignment of breadcrumb items with text that overflows the width
Before
After
=> fix(EG-1037): alignment of breadcrumb items with text that overflows the width

packages/back-end/src/infra/constructs/s3-construct.ts
Enforce SSL for S3 buckets
Enforces SSL for S3 bucket interactions to comply with AWS Audit requirements.
Calling BE api calls that use S3, such as list buckets or files from S3, and via the FE when uploading files as part of creating a run.
BE platform interactions with s3 are done via sdk anyway and are already compliant, presigned uploads are already ssl compliant.
=> feat(EG-964): enforce ssl for s3 buckets

packages/front-end/src/app/components/EGRunFormUploadData.vue
Remove unnecessary `isTrusted` check from file input handler
`isTrusted` property is a read-only property of Event objects that indicates whether or not the event was generated by a user action versus programmatically triggered. This error was triggered during a recent demonstration of the product in a closed network environment when attempting to add a file to the upload queue. While the error itself hasn't been reproducible in our dev environment, the handling of the error is largely redundant because:
1. Browser security already prevents programmatic file input manipulation
2. File selection still requires user interaction via system file picker
As such the error event handler can be safely removed to workaround the original issue.
Regression tested the file input mechanism.
No …
=> fix(EG-1038): remove redundant file input change error check

packages/front-end/src/app/components/EGBreadcrumbLabs.vue
Fix errors when switching lab via breadcrumb while on a nested lab page
Previously, the labs breadcrumb replaced only the `/lab/[labId]` part of the url, leaving any trailing characters. If you were on a nested page eg the run stepper, this caused errors.
Now, it replaces everything following `/lab/[labId]` as well so you land on the lab page no matter where you switched from.
=> fix(EG-1068): error when switching labs from breadcrumb while on a nested lab page eg stepper

packages/front-end/src/app/components/EGLabView.vue
Add the CreatedAt column to the lab runs table
Also changed: LastUpdated used to coalesce `LastUpdated ?? CreatedAt`, but as we now have the CreatedAt in its own column I made LastUpdated just show LastUpdated - see the row above without a LastUpdated value.
=> feat(EG-1065): add createdAt column as default sort and make lastUpdated only show changed date

packages/front-end/src/app/components/EGRunFormUploadData.vue
Communicate why the upload button is disabled for the more obscure reasons
This covers two cases which might be unclear:
- mix of single/pair files
- R2 file with no matching R1
The other reasons I concluded were clear enough and to add a message would be overexplaining:
- no internet connection
- no files selected yet
- upload is in progress
Tested those two cases, plus both at once, in which case it prioritizes the unmatched R2 message, which handily avoids the single/pair mix message also showing because the unmatched R2 is kind of treated as a single file
=> feat(EG-1053): communicate the more obscure reasons why the upload button would be disabled

packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue, packages/front-end/src/app/components/EGRunWorkflowFormEditParameters.vue, packages/front-end/src/app/components/EGS3SampleSheetBar.vue, packages/front-end/src/app/pages/labs/[labId]/run/[labRunId].vue, packages/front-end/src/app/pages/labs/[labId]/sample-sheet.vue
Display the sample sheet url to run details with open/copy/download functionality
This PR add sample sheet url (aka purple bar) to the Pipeline Run Details page.
The Sample Sheet URL component was modified to improve re-usability in the Pipeline Run Details page, Stepper 2 and Stepper 3 pages, and also extended to support the download functionality.
The Sample Sheet viewer display was also extended to include some extra metadata to provide some context on the samplesheet to aid re-usability in the future.
- Test a new Pipeline/Workflow launch and test the SampleSheet URL functionality to open/copy/download the samplesheet.
- Access a Pipeline Run Details page and test the SampleSheet URL functionality to open/copy/download the samplesheet.
None.
None.
=> feat(EG-1056): display the sample sheet url to run details with open/copy/download functionality

packages/back-end/src/infra/constructs/ses-construct.ts
Adds a more robust solution to render a divider line in Windows Outlook mail clients
Litmus to visually test against various Outlook versions.
=> fix(EG-1038): gray bar rendering in windows outlook

packages/front-end/src/app/components/EGRunFormUploadData.vue
Fix logic controlling if single upload retry is allowed
Retrying individual file uploads introduces edge cases where the file upload can get into invalid states and generate a sample sheet, eg. mix of single/paired or unpaired R2.
The previous logic applied to the paired-only approach from before the single file feature. The new logic just ensures that the above invalid states are inaccessible.
Tested that retry buttons are disabled for those two cases.
=> fix: retry upload allowed logic

packages/front-end/src/app/components/EGFileExplorer.vue, packages/front-end/src/app/pages/labs/[labId]/run/[labRunId].vue
Open File Browser to `/results`
When the File Browser loads in the S3 tree info, if the root dir contains a `results` dir in its children, it takes the step into that dir.
This will happen anywhere we have a File Browser - right now I believe that's just the results page but if we use it elsewhere we might need to make this feature optional.
=> feat(EG-1055): open file explorer to /results

packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/components/EGOrgView.vue, packages/front-end/src/app/pages/admin/orgs/create.vue, packages/front-end/src/app/pages/labs/create.vue
Change details tabs to say Settings
- Details -> Settings
- Lab Users -> Users
- create lab/org pages headers -> EGPageHeader
=> feat(EG-1073): change details tabs to settings and use page header on create lab/org pages

packages/front-end/src/app/components/EGBreadcrumbLabs.vue, packages/front-end/src/app/components/EGBreadcrumbOrgs.vue, packages/front-end/src/app/components/EGHeader.vue, packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/composables/useAuth.ts, packages/front-end/src/app/composables/useUser.ts, packages/front-end/src/app/pages/index.vue, packages/front-end/src/app/stores/user.ts
Changes:
- bc8e3ac: refactor(EG-1052): rename currentLab -> mostRecentLab because unlike currentOrg there is not a global current lab
Thinking in terms of "current lab" is subtly very misleading. This has previously caused components (specifically the pinia stores) to be designed under the assumption of there being a single, current lab, like an app. This has incurred sizeable refactoring work in the past because EasyG is a website and can have multiple tabs with multiple labs open at the same time (unlike orgs - there really is a single current org). I've called the lab store `mostRecentLab` because that's what it really is.
- 9758fba: refactor(EG-1052): move most recent lab logic to root page
The "open the most recent lab if available" logic is useful outside of just signing in. A user …
=> feat(EG-1052): meta PR

packages/front-end/src/app/components/EGFileExplorer.vue, packages/front-end/src/app/stores/ui.ts
Add an open button for HTML files
Open button makes behaviour clearer and shows visual feedback while loading.
=> feat(EG-1076): add open button for html files

packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/front-end/src/app/components/EGRunFormUploadData.vue, packages/front-end/src/app/components/EGS3SampleSheetBar.vue, packages/front-end/src/app/composables/usePipeline.ts, packages/shared-lib/src/app/schema/easy-genomics/upload/s3-file-upload-sample-sheet.ts, packages/shared-lib/src/app/types/easy-genomics/upload/s3-file-upload-sample-sheet.d.ts
Enhance samplesheet csv name to inc run name
This PR improves the SampleSheet generation API to save the Sample Sheet csv file on S3 with the Run Name to make it easier for reviewing files on S3, and also make the Sample Sheet csv file downloaded filename consistent between the Sample Sheet purple bar and the File Manager.
Instead of the Sample Sheet csv file being saved as `samplesheet.csv` it is now saved as `samplesheet-{Run Name}.csv`.
None.
None.
=> feat(EG-1077): enhance samplesheet csv name to inc run name

packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
This to correct the name of the Users and Settings tab which was missed in the previous PR
Additional fix for the renamed tabs (Users & Settings)
Test case passed locally
This only affects 1 file - Organizations_System_Admin.spec.e2e.ts
None
=> fix(EG-1084): update lab users and settings tabs

packages/back-end/src/app/controllers/easy-genomics/organization/create-organization.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/organization/update-organization.lambda.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/back-end/src/main.ts, packages/shared-lib/src/app/schema/easy-genomics/organization.ts, packages/shared-lib/src/app/types/easy-genomics/organization.d.ts, packages/shared-lib/src/app/types/easy-genomics/sample-data.ts
Update Organization create/update APIs to support `NextFlowTowerApiBaseUrl` setting
This PR enhances the existing Organization `create-organization` and `update-organization` API endpoints to support the the `NextFlowTowerApiBaseUrl` setting at the Organization level. 
If it is undefined, it will default to the value set in Back-End main stack's `seqeraApiBaseUrl` setting, which defaults to `https://api.cloud.seqera.io` or can be overridden by the optional `easy-genomics.yaml` > `back-end` > `seqera-api-base-url`  configuration parameter.
This enhancement is to allow the FE to easily obtain the associated parent Organization's `NextFlowTowerApiBaseUrl` value when creating a new Laboratory, or updating an existing Laboratory to make the Laboratory's Seqera Base API URL more visible and …
=> feat(EG-1087): update Organization create/update APIs to support NextFlowTowerApiBaseUrl setting

packages/back-end/src/app/controllers/easy-genomics/laboratory/run/list-laboratory-runs.lambda.ts, packages/back-end/src/app/utils/rest-api-utils.ts, packages/front-end/src/app/repository/modules/labs.ts
Add filtering support for list-laboratory-runs API
This PR adds logic to support filtering for the `/easy-genomics/laboratory/run/list-laboratory-runs` API to support filtering by one or more properties in the `LaboratoryRun` object type through the use of query parameters.
The filtering is performed in the order of the supplied query parameters, and the query parameters must match the `LaboratoryRun`'s property names and property value stored in the database record (i.e. it is case-sensitive).
e.g.
- `/easy-genomics/laboratory/run/list-laboratory-runs?LaboratoryId={LabId}&Status=COMPLETED`
The filtering also supports partial filtering by the supplied value with the use of '*' character.
e.g.
- `/easy-genomics/laboratory/run/list-laboratory-runs?LaboratoryId={LabId}&RunName=*-my-test-run-n …
=> feat(EG-1054): add filtering support for list-laboratory-runs API

packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/components/EGTable.vue, packages/front-end/src/app/repository/modules/labs.ts
Implement My Own Runs filter checkbox using new BE filtering function
When checkbox is changed, the runs are refetched from the BE using the server-side filter.
The table behaves correctly in displaying the updated rows. Testing included:
- filtered values were less than 1 page - pagination disappeared ✅ 
- filtered values were more than 1 page - pagination worked as expected ✅ 
- sort remains across filter changes and results follow sort in all cases ✅ 
- Future design changes may be implemented in further PRs pending designs being created for this feature.
=> feat(EG-1071): filter my own runs with run table BE sort

packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/repository/modules/omics-runs.ts
Implement cancelling Omics runs
I must have missed this a while back and it's never come up until now.
The cancel request is sent. However it seems that at the moment, cancel requests for either type of runs are failing. We'll look into this soon.
=> feat: implement cancelling omics runs

packages/back-end/src/app/controllers/easy-genomics/laboratory/create-laboratory.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/update-laboratory.lambda.ts, packages/front-end/src/app/components/EGFormLabDetails.vue, packages/shared-lib/src/app/utils/HttpError.ts
Update BE laboratory APIs test call to seqera to use NextFlowTowerApiBaseUrl
This PR fixes the Seqera API test logic used in the `/easy-genomics/laboratory/create-laboratory` and `/easy-genomics/laboratory/update-laboratory` APIs to use the Lab's supplied `NextFlowTowerApiBaseUrl` instead of the BE configuration value.
It also fixes the FE CreateLaboratory Settings UI to make the `NextFlowTowerAccessToken` field mandatory only when creating a new Laboratory.
None.
None.
=> fix(EG-1092): update BE laboratory APIs test call to seqera to use NextFlowTowerApiBaseUrl

packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/components/EGTable.vue
Fix table multi-page sort not working again because of the filter feature
Now, the table data is refetched on sort change, as it should
=> fix: table multi-page sort broken by filter feature

packages/front-end/src/app/components/EGFormOrgDetails.vue, packages/front-end/src/app/components/EGOrgView.vue, packages/front-end/src/app/pages/admin/orgs/create.vue, packages/front-end/src/app/repository/modules/orgs.ts, packages/front-end/src/app/types/forms.ts
Add Default Seqera Endpoint URL field to Org settings
Tested saving and creating with values, and blank input which gets set to config default
=> feat(EG-1095): add default seqera endpoint url field to org settings

packages/front-end/src/app/components/EGLabView.vue
Update FE EGLabView.vue filter by current User to use UserId instead of email string
This PR improves the reliability of the LaboratoryRun listing's filtering by the current User. 
This is done by switching from the filtering parameter from:
- `/easy-genomics/laboratory/run/list-laboratory-runs?LaboratoryId={Lab ID}&Owner={User Email}` 
to 
- `/easy-genomics/laboratory/run/list-laboratory-runs?LaboratoryId={Lab ID}&UserId={User ID}`
None.
None.
=> fix(EG-1099): update FE EGLabView.vue filter by current User to use UserId instead of email string

packages/front-end/src/app/components/EGBreadcrumbOrgs.vue, packages/front-end/src/app/components/EGDialog.vue, packages/front-end/src/app/components/EGHeader.vue, packages/front-end/src/app/components/EGSwitchOrgModal.vue, packages/front-end/src/app/stores/ui.ts
Fix problems with org switching:
- unexpected delay on switch
- current lab persisted across org switch
Firstly, refactored the org switching code into a component, deduplicating it across header/org breadcrumb.
Then, fixed unexpected delay after org switch visible loading:
- previously, it had the artificial delay, then the network call to update last org (this was the unexpected delay)
- now, the network call is the delay
Also, fixed the current lab persisting across org switch - it was related to the app remount (`incrementRemountAppKey`) interrupting the re-routing logic that would take the page to the proper destination. I fixed it with a 100ms delay; I would much rather remove the app remount, but I don't know why it's there and I don't have the bandwidth atm to figure out if …
=> fix(EG-1096): switch org problems

packages/front-end/src/app/components/EGFormLabDetails.vue, packages/front-end/src/app/types/labs.ts
Fixed the lab creation bug Kelsey showed in the meeting.
Worthy of note is that this bug only occurred due to the org not having a Seqera endpoint URL, which is due to an outdated backend or outdated data. This shouldn't persist but this patch fixes it anyway.
I couldn't replicate the issue myself but this is a common sense change and it works fine.
=> fix(EG-1097): create lab prevented when seqera endpoint url not available but seqera is not enabled

packages/back-end/src/app/controllers/easy-genomics/laboratory/pipeline/update-laboratory-pipelines.lambda.ts, packages/back-end/src/app/services/easy-genomics/laboratory-pipeline-service.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/front-end/src/app/components/EGFormLabDetails.vue, packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/repository/modules/labs.ts, packages/shared-lib/src/app/schema/easy-genomics/laboratory-pipeline.ts, packages/shared-lib/src/app/schema/easy-genomics/laboratory.ts, packages/shared-lib/src/app/types/easy-genomics/laboratory.d.ts
BE support for lab pipeline/workflow restrictions
This PR adds a new BE API `/easy-genomics/laboratory/pipeline/update-laboratory-pipelines/:id` to enable an OrganizationAdmin to restrict the Seqera Cloud pipelines / AWS HealthOmics workflows for a specific Laboratory.
The API expects the UpdateLaboratoryPipelines DTO which is of the following example structure:
```
{
"AwsHealthOmicsWorkflows": {
"1873109": true,
"5073962": true
},
"NextFlowTowerPipelines": {
"8098098309890": true,
"12321989789789": true
}
}
```
Both the `AwsHealthOmicsWorkflows` and `NextFlowTowerPipelines` details are updated directly into the Laboratory dynamodb record.
The FE EGFormLabDetails has also been updated to call this API to save the changes.
None.
None.
=> feat(EG-1088): BE support for lab pipeline/workflow restrictions

packages/back-end/src/app/controllers/easy-genomics/laboratory/run/process-update-laboratory-run.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/laboratory/run/request-laboratory-run-status-check.lambda.ts, packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts, packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts, packages/front-end/src/app/components/EGLabView.vue, packages/front-end/src/app/repository/modules/labs.ts
This PR includes a new lambda function that handles requests from the front-end to check the status of any run that is not in a terminal state. The lambda function publishes an message to the laboratory run update topic which eventually causes the process-update-laboratory-run to determine the status of the runs. A change was added to the front-end where a table refresh key was added and the fetchLaboratoryRuns() function was removed. This enables the table to be updated and refreshed without the user needing to manually reload the page.
I've also included an unrelated minor bug fix that removes the spaces from samplesheet, which causes problems in a number of pipelines.
I have tested this with healthomics runs to see the status update changes. I am unsure if any built in validations or …
=> feat: run status update redesign
