twobulls/easy-genomics

- packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue
Removes upload timeout preventing large files from uploading. 
Simplifies and improve display logic for remove button, upload button and dropdown.
> fix(EG-616): file upload

- packages/front-end/src/app/components/EGToast.vue
Reinstates missing toast icons due to incorrect prop names being passed. 
Also implemented themed progress meter and minor style improvements to better align with designs.
> fix(EG-623): missing toast icons + improved styles

- packages/back-end/src/app/controllers/aws-healthomics/private-workflow/create-private-workflow.lambda.ts
- packages/back-end/src/app/controllers/aws-healthomics/private-workflow/delete-private-workflow.lambda.ts
- packages/back-end/src/app/controllers/aws-healthomics/private-workflow/list-private-workflows.lambda.ts
- packages/back-end/src/app/controllers/aws-healthomics/private-workflow/read-private-workflow.lambda.ts
- packages/back-end/src/app/controllers/aws-healthomics/private-workflow/request-private-workflow.lambda.ts
- packages/back-end/src/app/controllers/aws-healthomics/private-workflow/update-private-workflow.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/list-laboratories.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/read-laboratory.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/request-laboratory.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/create-organization.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/delete-organization.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/list-organizations.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/read-organization.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/update-organization.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/user/add-organization-user.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/user/edit-organization-user.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/user/list-organization-users-details.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/user/list-organization-users.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/user/remove-organization-user.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/user/request-organization-user.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-request.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/user/confirm-user-forgot-password-request.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/user/create-user-forgot-password-request.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/user/create-user-invitation-request.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/user/create-user.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/user/list-all-users.lambda.ts
Uses the `buildResponse` for all error responses so that the correct headers are applied.
> chore: use correct headers for error responses

- packages/front-end/src/app/pages/labs/[labId]/index.vue
Adds the `userName` value to a new "Owner" column in the Lab's Runs tab
> feat(EG-679): add userName data to runs tab

- packages/back-end/src/infra/constants/cognito.ts
- packages/back-end/src/main.ts
- packages/back-end/test/infra/constants/cognito.test.ts
We check the password strength per the cognito spec before deploying to prevent failed deployments.
> feat: cognito password strength check during build

- packages/front-end/tests/e2e/EditLab.spec.e2e.ts
This pr will add 5000 timeout when
a. After removing a Lab
b. After saving Lab changes
> feat(EG-724): add new timeout in EditLab

- packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue
- packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue
- packages/front-end/src/app/composables/usePipeline.ts
Checks if all param properties in a given section are flagged as `hidden` and if true hides their parent section heading from the sidebar UI.
> fix(EG-718): hide params section if its items are all hidden

- packages/front-end/src/app/components/EGStatusChip.vue
https://dept-au.atlassian.net/browse/EG-573
> feat(EG-573): make submitted pill grey

- packages/front-end/src/app/pages/labs/[labId]/[workflowId]/index.vue
Fixes a typo in the Lab Run Results page.
> fix(EG-730): typo

- packages/front-end/src/app/components/EGLabDetailsForm.vue
- packages/front-end/src/app/components/EGSelect.vue
This PR changes the behaviour of the S3 bucket select menu when creating a new Lab to display a placeholder instead of defaulting to the first S3 bucket in the list.
> feat(EG-731): no default s3 bucket when creating lab

- packages/front-end/tests/e2e/CreateLab.spec.e2e.ts
Added selection of S3 bucket when creating a Lab
> feat(EG-737): add S3 bucket selection in CreateLab

- .github/workflows/cicd-release-sandbox.yml
- .projenrc.ts
- pnpm-lock.yaml
This PR aims to fix the CI/CD deployment error for quality.dev.easygenomics.org.
It also fixes the CI/CD release template for sandbox to restrict it when the branch name starts with `infra/*`.
> fix(eg-747): update packages to fix front-end deployment

- packages/front-end/src/infra/constructs/www-hosting-construct.ts
This PR improves upon the CloudFront distribution logging to make it easier to clean up the deployment without running into non-empty access-log S3 Bucket error.
- It reduces the logging window to 1 day (minimum)
- It also only enables the CloudFront distribution logging for non-Dev deployments (e.g. Demo Pre-Prod).
> fix(EG-748): update www-hosting-construct to improve cloudfront dist logging

- packages/back-end/src/app/controllers/easy-genomics/laboratory/read-laboratory.lambda.ts
This PR updates the `/easy-genomics/laboratory/read-laboratory` API to allow an OrganizationAdmin to access it properly and thus allow them to access the Laboratory.
Removed the `TODO: Laboratory not found` comment. 
When Laboratory is not found by the `queryByLaboratoryId()` it will throw a LaboratoryNotFoundException() and this is caught and returned by the `read-laboratory` API to the FE to handle.
> fix(EG-754): update read-laboratory API to allow OrganizationAdmin access

- packages/front-end/src/app/components/EGLabDetailsForm.vue
Adds asterixes to two fields in the "Create a Lab" page, denoting them as mandatory fields.
> feat(EG-736): add mandatory labels to existing form fields

- packages/front-end/src/app/pages/labs/[labId]/[workflowId]/index.vue
- packages/front-end/src/app/stores/ui.ts
This fixes the Lab Run's Details page regression so the details can load properly.
> fix(EG-802): fix Lab Run Details page regression

- .projenrc.ts
Fixes a typo in the e2e command for CI/CD execution.
> fix(EG-819): test script typo

- packages/front-end/package.json
Projen update to `package.json` script
> feat(EG-819): projen update

- packages/back-end/src/app/controllers/easy-genomics/laboratory/list-laboratories.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/organization/list-organizations.lambda.ts
- packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
Finds the user from their email address instead of the cognito id, which might not match up to the user inside dynamodb
> fix: use email address to find user instead of cognito id

- config/easy-genomics.example.yaml
- packages/front-end/config/env-config.ts
- packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
- packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
Various improvements and fixes for `Organizations_System_Admin.spec.e2e.ts`:
- adds `exact: true` option for string specificity
- camelCase variables for consistency
- add uuid to randomize string to prevent test breakage due to previous test failures
> fix(EG-821): e2e test improvements

- .github/workflows/cicd-release-quality.yml
- .github/workflows/cicd-release-sandbox.yml
- packages/front-end/config/env-config.ts
- packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
- packages/shared-lib/src/app/types/configuration.d.ts
- projenrc/github-actions-cicd-release.ts
Various fixes for test env vars and config.
All tests are passing when run locally except for "Invite a user to an Org successfully" - this is due to the existing email verifications issue in AWS SES - PR here: https://github.com/twobulls/easy-genomics/pull/398
> fix(EG-821): fix e2e tests

- packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
Adds more specificity to the Admin table selectors plus some additional logging for easier future debugging.
> fix(EG-821): specific selector + better logging

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
- packages/front-end/tests/e2e/lab-technician/Labs_Lab_Technician.spec.e2e.ts
This PR contains new scripts for checking the permission on
- if organizations menu/link can be accessed
- if remove lab option is visible
- if create new lab button is visible
> feat(EG-837): lab manager and technician scripts

- packages/back-end/src/app/controllers/easy-genomics/upload/create-file-upload-sample-sheet.lambda.ts
Uses the sample name determined and supplied from the FE in the CSV file.
> fix(EG-831): fix sample name in csv

- packages/front-end/src/app/components/EGFormOrgDetails.vue
- packages/front-end/src/app/components/EGPageHeader.vue
Disables input fields and adds a loading/disabled state to the "Save changes" button when editing Org details.
> fix(EG-818): org details disabled/loading states while editing

- packages/front-end/src/app/components/EGOrgView.vue
- packages/shared-lib/src/app/schema/configuration.ts
Fixes a regression caused by an `org` computed property returning `undefined` due to the data not being made available at time of declaration.
> fix(EG-821): org is undefined in Org View

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/components/EGLabsList.vue
- packages/front-end/src/app/components/EGOrgView.vue
- packages/front-end/src/app/components/EGOrgsList.vue
- packages/front-end/src/app/components/EGUserAccess.vue
- packages/front-end/src/app/pages/labs/index.vue
- packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
Also contains a test refactor to pass inviting a Lab user.
> fix(EG-853): hide create lab button for Lab Manager/Technician

- packages/back-end/src/app/controllers/easy-genomics/laboratory/delete-laboratory.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/process-delete-laboratory.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/run/create-laboratory-run.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/run/delete-laboratory-run.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/run/list-laboratory-runs.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/run/read-laboratory-run.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/laboratory/run/update-laboratory-run.lambda.ts
- packages/back-end/src/app/controllers/nf-tower/workflow/create-workflow-execution.lambda.ts
- packages/back-end/src/app/services/easy-genomics/laboratory-run-service.ts
- packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
- packages/back-end/src/infra/stacks/nf-tower-nested-stack.ts
- packages/shared-lib/src/app/schema/easy-genomics/laboratory-run.ts
- packages/shared-lib/src/app/types/easy-genomics/laboratory-run.d.ts
- packages/shared-lib/src/app/types/easy-genomics/sns-processing-event.d.ts
- packages/shared-lib/src/app/utils/HttpError.ts
> feat(EG-861): laboratory runs apis

- packages/front-end/src/app/components/EGRunPipelineParameterInputs.vue
Fixes issue with the `input` field not updating when moving between Step 3 and Step 4.
> fix(EG-768): stepper input field not updating

- packages/back-end/src/app/controllers/easy-genomics/user/delete-user-request.lambda.ts
- packages/back-end/src/app/controllers/easy-genomics/user/process-delete-user.lambda.ts
- packages/back-end/src/app/services/cognito-idp-service.ts
- packages/back-end/src/app/services/easy-genomics/user-service.ts
- packages/back-end/src/infra/stacks/easy-genomics-nested-stack.ts
Allows the deletion of a users account, including their cognito account, laboratory user and organization user.
> feat: user delete api

- packages/front-end/src/app/components/EGUserAccess.vue
Prevent superuser from editing user access to labs
Manually checked controls are disabled for superuser, and still enabled for other users
> fix(EG-880): prevent superuser from editing user access to labs

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue
- packages/front-end/src/app/composables/useFileDownload.ts
- packages/front-end/src/app/pages/labs/[labId]/[nextFlowRunId]/index.vue
- packages/front-end/src/app/pages/labs/[labId]/[pipelineId]/run-pipeline.vue
- packages/front-end/src/app/plugins/api.ts
- packages/front-end/src/app/repository/modules/nextflow-pipelines.ts
- packages/front-end/src/app/repository/modules/nextflow-runs.ts
- packages/front-end/src/app/stores/run.ts
- packages/front-end/src/app/stores/ui.ts
- packages/shared-lib/src/app/types/nf-tower/nextflow-tower-api.ts
Change NextFlow-specific variables/functins/interfaces to include explicit reference to NextFlow
This is a refactor to add "nextFlow" to NextFlow-specific stuff, in preparation for implementing Omics stuff alongside them.
This patch should have no functional change on the application.
e2e tests passed in build2
Zero functional impact.
> refactor(EG-873): nextflow variables names

- packages/back-end/src/app/controllers/nf-tower/workflow/create-workflow-execution.lambda.ts
- packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue
Reverts twobulls/easy-genomics#460
> fix(EG-888): revert store FE transactionId as LaboratoryRun runId

- packages/front-end/src/app/components/EGHeader.vue
- packages/front-end/src/app/layouts/password.vue
- packages/front-end/src/app/pages/profile.vue
- packages/front-end/src/app/stores/ui.ts
- packages/front-end/src/app/types/user.ts
Implement the profile page
Profile page is implemented, except for sending off the details update. Will come later when API is ready.
Minimal testing applicable as new page with no major moving parts. A new e2e test will be added with the implementation of the details update.
> feat(EG-410): profile page

- packages/front-end/src/app/components/EGHeader.vue
Fix profile chevron not right aligned
Before
After
> fix: profile chevron not right aligned

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
New script for running/launching a Seqera pipeline
This change will add automation for launching a Seqera Run which will sit under the Lab Manager role / scripts
Ran the scripts few times and new runs are reflected in the Runs tab
This will impact the 'Labs_Lab_Manager.spec.e2e.ts' file only.
This will add a new file under ./tests/e2e/fixtures for the sequencing files essential for running the WF
IMPORTANT: The lab to be used must be Seqera enabled and therefore the WS ID must be updated. Details to be provided in slack.
> feat(EG-687): launch seqera runs

- packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
New script to update lab and enable OMICS integration. 
Ran the script against 2 scenarios:
1. When toggle is off
2. When toggle is already on
This is within **Labs_Org_Admin.spec.e2e.ts** only
> feat(EG-900): enable omics integration

- packages/front-end/src/app/composables/useUser.ts
- packages/front-end/src/app/pages/profile.vue
- packages/front-end/src/app/repository/modules/users.ts
- packages/front-end/src/app/stores/user.ts
- packages/front-end/tests/e2e/lab-technician/Profile_Lab_Technician.spec.e2e.ts
Implement updating first and last name from the profile page
Wires up the profile page names form to the new API endpoint.
e2e test added to verify function.
> feat(EG-410): update names

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
- packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
**Labs_Org_Admin.spec.e2e.ts**
- Refined ‘07 - Add a Lab Manager to a Laboratory Successfully’ to add a step to change access role from Lab Tech no Lab Manager
- New Scripts:
- 09 - Add a Lab Technician to a Lab Successfully
**Labs_Lab_Manager.spec.e2e.ts**
New Scripts:
-   06 - Remove user from a Laboratory Successfully
-   07 - Add a Lab Technician to a Lab Successfully
Re-run the scripts multiple times in Quality environment until all passed.
Impacts the following files:
1. **Labs_Org_Admin.spec.e2e.ts**
2. **Labs_Lab_Manager.spec.e2e.ts**
> feat(EG-902): add and remove lab technician

- packages/front-end/tests/e2e/lab-technician/Profile_Lab_Technician.spec.e2e.ts
This is a new script to test user has access to reset password via the profile menu
Re-ran the script few times as Lab Technician
This will impact this file - **Profile_Lab_Technician.spec.e2e.ts** only
- [X No new errors or warnings have been introduced.
> feat(EG-894): reset password via profile menu

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue
- packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue
- packages/front-end/src/app/components/EGRunPipelineFormRunDetails.vue
- packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue
- packages/front-end/src/app/components/EGRunPipelineStepper.vue
- packages/front-end/src/app/composables/usePipeline.ts
- packages/front-end/src/app/pages/labs/[labId]/run-pipeline/[pipelineId].vue
- packages/front-end/src/app/stores/index.ts
- packages/front-end/src/app/stores/labs.ts
- packages/front-end/src/app/stores/run.ts
- packages/front-end/src/app/stores/seqeraPipelines.ts
Fix the Launch Another Workflow Run button not working
This required quite a lot of refactoring to make the run-pipeline page self-contained (not reliant on data set by the previous page).
With that done, the fix was as simple as reloading the page with a new temp id.
e2e tests pending
> fix(EG-886): launch another workflow run

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue
- packages/front-end/src/app/components/EGRunPipelineFormReviewPipeline.vue
- packages/front-end/src/app/pages/labs/[labId]/run-pipeline/[pipelineId].vue
Support new NF Tower schema with `definitions` changed to `$defs`
Change references to `definitions` to use `$defs` if present, otherwise default to existing `definitions`
Testing ability limited at this point, but pipeline run succeeded post changes
> feat(EG-907): schema $defs

- packages/front-end/src/app/components/EGHeader.vue
- packages/front-end/src/app/composables/useUser.ts
Update organization spelling where spelled with an s
> chore(EG-903): update organization spelling where spelled with an s

- LICENSE
- packages/back-end/LICENSE
- packages/front-end/LICENSE
- packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue
- packages/shared-lib/LICENSE
Adds a toast message specifically if a network error times out the upload process.
Refactored `uploadfile()` and `uploadFiles()` for a bit more clarity. Replaced the boolean `anyRejected` that indicates overall pass/fail of upload process with `failedUploads`array that does a check on individual file uploads, allowing for more granular errors.
Unrelated: updated licenses year from 2024 -> 2025 in relevant `LICENSES` files.
Manual exploratory.
> feat(EG-639): file upload error handling

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Add new View Run Details scripts
This PR adds new scripts for the Lab Manager test suite (Script #9).
Ran the whole Lab Manager scripts several times and passed.
The impact is only on the Labs_Lab_Manager.spec.e2e.ts
> feat(EG-914): add view Run Details scripts

- packages/front-end/src/app/components/EGHeader.vue
- packages/front-end/src/app/components/EGUserDisplay.vue
- packages/front-end/src/app/composables/useUser.ts
- packages/front-end/src/app/repository/modules/users.ts
- packages/front-end/src/app/stores/ui.ts
- packages/front-end/src/app/stores/user.ts
Add clickable stars to indicate and set default org
e2e tests pending
> feat(EG-917): default org stars

- packages/front-end/tests/e2e/lab-technician/Profile_Lab_Technician.spec.e2e.ts
Fix the failing automation script on the profile name change
This fix is to add a short code for lines 26 & 62 so that even if similar texts exists, the script will always look for the exact.
Ran script #1 few times with passed result
Affects Profile_lab_Technician.spec.e2e.ts
None
> fix(EG-930): fix profile name change scripts

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/pages/labs/[labId]/omics-run/[omicsRunId].vue
- packages/front-end/src/app/pages/labs/[labId]/seqera-run/[seqeraRunId].vue
Updates "Run Results" tab label to "File Manager"
> feat(EG-928): update tab name

- packages/front-end/src/app/components/EGHeader.vue
Replace the default org stars with the new radio-button-esqe design
The style also changes when clicked to indicate processing
> feat(EG-917): replace stars with new buttons design

- packages/back-end/src/app/controllers/easy-genomics/laboratory/run/create-laboratory-run.lambda.ts
Trigger status checks on laboratory run creation
Previously the laboratory runs were being updated with the ExternalRunId which would then trigger the status check, but now are being created with those id's from the FE. The create had permissions to for the SNS queue but didn't have the code to trigger the status check.
Create a run and then wait 5 minutes for it to update
> fix: trigger status checks on creation of lab runs

- packages/front-end/src/app/pages/labs/[labId]/run/[labRunId].vue
- packages/front-end/src/app/stores/ui.ts
Add a row to the Lab Run page with a Download button for the sample sheet
This just makes it easier to download the sample sheet instead of having to get it from the File Manager
> feat(EG-925): implement sample sheet download

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/components/EGTable.vue
Sort Lab Run table
Enables sorting Lab Run table by any column. Sorts by Last Updated by default.
> feat(EG-937): implement sorting lab run table by any column with last updated by default

- packages/front-end/tests/e2e/lab-manager/Profile_Lab_Manager.spec.e2e.ts
Added new scripts to change profile name and reset password as a Lab Manager
This is an additional new file to the lab-manager test suite - Profile_Lab_Manager.spec.e2e.ts
This only a copy from the existing profile scripts for a lab technician with very minor tweaks.
Ran the scripts with pass results
This doesn't update any existing script. This is a new file added Profile_Lab_Manager.spec.e2e.ts
> feat(EG-947): profile scripts for lab manager

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
- packages/front-end/tests/e2e/lab-manager/Profile_Lab_Manager.spec.e2e.ts
Create scripts to check if files exist in the File Manager of the launch run + Remove failing profile script
The changes include:
1. Check if files exist in File Manager and click download
2. Remove the profile name change scripts due to constant failure
Tested and passed
2 files were impacted
1. Labs_Lab_Manager.spec.e2e.ts
2. Profile_Lab_Manager
> feat(EG-924): create file manager scripts

- packages/shared-lib/src/app/types/easy-genomics/sample-data.ts
Fix default settings for seeded Organization to support testing.
Fix default settings for seeded Organization.
None.
None.
None.
> fix(EG-741): update seeded Organization settings to enable HealthOmics & Seqera Cloud

- packages/front-end/src/app/components/EGRunPipelineFormUploadData.vue
Stepper step 2  file uploader restyle.
Restyles Step 2's file upload UI to use an animated green gradient to indicate progress over time. Uploads are now tracked independently and can pass/fail as seperate executions.
Tested manually with various sample file pairs.
Logic for the error states has been removed temporarily and will be re-added in the subsequent ticket. The existing error code was not compatible with this current refactor. This area has no existing e2e test coverage so will not cause any breakage.
- [  ] Documentation has been updated accordingly.
- [  ] Code has been commented in particularly hard-to-understand areas.
> feat(EG-705): file upload progress re-style

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Update launch seqera and view run details script
This PR includes:
1. Fix for the failing launch Seqera scripts
2. Fix for the failing View Run Details scripts
3. Fix for the failing View File Manager scripts
4. Added few more tests within View Run Details scripts
Ran the scripts few times with pass result
This change affects only 1 file - Labs_Lab_Manager.spec.e2e.ts
> feat(EG-955): update launch seqera scripts

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Fix the existing issues on the failing view run details and file manager
This is to fix the locators used in playwright; the value of the runName is saved in a new variable which seems to work locally
Tested and passed locally
Labs_lab_Manager.spec.e2e.ts file only
> fix(EG-967): fix failing scripts

- packages/back-end/src/app/controllers/easy-genomics/laboratory/update-laboratory.lambda.ts
Skip NF Access Token check if not using NF Tower
On updates, the api endpoint will check for the NF Access Token, but if the lab is AWS Omics only, it will not have an entry in the parameter store at all for the lab and the get parameter call will fail.
This change will restrict the update call to only check the token if the lab is NF Tower enabled.
Create a lab without seqera
load lab again, don't touch the seqera settings, update an unrelated field (description) and try to save
Will present this error
Prevents updating of AWS Omics only labs
Will now also catch the error if the parameter doesn't exist and send back a different error message. This will make future debugging of errors easier.
> fix: skip token check if not using nf tower

- packages/front-end/src/app/components/EGLabView.vue
Add an action on Lab Run to link to the File Manager tab instead of the default Run Details
> feat(EG-950): add action link to file manager

- packages/back-end/src/infra/stacks/back-end-stack.ts
Suppress warnings about no authorizers on public endpoints
We don't need authorizers for our public endpoints
No testing required
none
Just suppresses warning
> chore: suppress warnings about no authorizers on public endpoints

- packages/front-end/src/app/components/EGRunFormUploadData.vue
Various refactors to clean up and improve file uploading
- replaces state management/refs with computeds where possible
- fixes issues with upload files UI elements being disabled in some cases where they shouldn't
- EG-984: fixes bug where errors did not reset on upload retry
- makes upload manifests only include files being uploaded (ie does not include completed files on retry)
- allows uploading additional files after successful upload
- retrieve sample sheet info once all uploads have succeeded, including after retries
These changes are useful on their own but are also pre-work to make file state persistence simpler and more robust.
This has all been manually tested and should be working right but any edge cases that I've missed may shake out in the near future.
> refactor: uploads

- packages/front-end/src/app/components/EGRunFormUploadData.vue
Fix error in pre-upload manifest retrieval leaving app state stuck on uploading
I happened to get an error back from the pre-upload manifest retrieval API call and it left the app stuck on Uploading... which the user had no way out of other than starting over with a new run. This fixes that by adding an error to the files that were being uploaded so that the state goes to error.
> fix: error in pre-upload manifest retrieval leaving app state stuck on uploading

- packages/front-end/src/app/components/EGRunFormUploadData.vue
Various fixes and improvements for file uploads 
- Reverted file duplication check to previous implementation for robustness
- Modified `getFileDetails` to properly reset file state - this fixes a bug when trying to re-add a file that had been prevoip:
- `progress: undefined`
- `error: undefined`
- `url: undefined`
- Improved validation logic for file pairs
- Refactored boolean check for s3 url availability and re-wired the `Download sample sheet` button so it displays at the same time as the sample sheet URL bar
Manually tested scenarios
> fix(EG-931): file upload improvements

- packages/front-end/src/app/components/EGRunFormUploadData.vue
Allow uploading single files
Implements file pair sorting logic in accordance with design:
Also adds the trash button to pending upload files and successfully uploaded files. It looks kinda wonky but we can tweak that.
Extensively... But there are a lot of cases and I'm going to keep trying to break it.
> feat(EG-601): allow uploading single files

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Launch Health OMICS run
This is additional scripts to:
1. Launch an OMICS run
2. View the OMICS Run details
3. VIew the file manager for an OMICS run
Ran the scripts with pass result
Only affects 1 file - Labs_Lab_Manager.spec.e2e.ts
> feat(EG-895): launch omics workflow

- packages/front-end/src/app/components/EGRunFormUploadData.vue
Fixes S3 sample sheet URL bar not appearing after successful re-tried upload.
Mutated prop `props.wipRun` was throwing an error that prevented the computed property boolean `hasSampleSheetUrl`  from re-calculating and triggering the URL bar from appearing.
Repeated manual tests for multi-file uploads.
> fix(EG-993): sample sheet url bar visibility

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Updated the variable causing the issue 'ReferenceError: runName is not defined'
Re-arranged the sequence of the tests
All tests passed within Labs_Lab_Manager.spec.ts.e2e
Only affects Labs_Lab_Manager.spec.ts.e2e
> fix(EG-1019): fix failing test scripts

- packages/front-end/src/app/components/EGUserOrgAdminToggle.vue
Just removes a word from a toast that shouldn't be there
> fix(EG-463): org admin toggle toast referencing "Lab" erroneously

- packages/front-end/src/app/components/EGBreadcrumbLabs.vue
- packages/front-end/src/app/components/EGBreadcrumbOrgs.vue
- packages/front-end/src/app/components/EGOrgView.vue
- packages/front-end/src/app/components/EGUserAccess.vue
Fix breadcrumbs for superuser, and add some more breadcrumbs where they logically should be
Manually tested each of the above cases plus checked existing features for regressions
> fix(EG-1024): breadcrumbs not working for superuser and add some more crumbs

- packages/front-end/src/app/components/EGRunFormUploadData.vue
> fix(EG-1015): sample id and file name overlapping on narrow window sizes

- packages/front-end/src/app/pages/labs/[labId]/run-pipeline/[pipelineId].vue
- packages/front-end/src/app/pages/labs/[labId]/run-workflow/[workflowId].vue
Reset step 3 params when all files are removed
When there have been files added, and they are all deleted, the deletion of the final file triggers a reset of the params for the pipeline run
Tested working on Seqera and Omics
> fix(EG-1035): reset step 3 params on removal of all files

- packages/front-end/src/app/components/EGLabView.vue
Move Lab Runs tab to position 1 and rename to Pipeline Runs
> feat(EG-1058): move lab runs to position 1 as pipeline runs

- packages/back-end/src/infra/constructs/api-gateway-construct.ts
API Gateway logging
This enables logging for API Gateway to satisfy HIPAA requirements
API calls should be logged to a cloudwatch group
Logging is enabled for dev, but it shouldn't exceed the free tier limits.
> feat(EG-963): api gateway logging

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Update scripts to use Pipeline Runs tab instead of Lab Runs
This is a minor script change due to ticket EG-1058 to update the name of Lab Runs to Pipeline Run
All scripts passed locally
Only affects Labs_Lab_Manager.spec.e2e.ts
> fix(EG-1070): update pipeline runs test

- packages/front-end/src/app/components/EGRunFormUploadData.vue
- packages/front-end/src/app/components/EGRunPipelineFormEditParameters.vue
- packages/front-end/src/app/components/EGRunWorkflowFormEditParameters.vue
- packages/front-end/src/app/composables/useMultiplatform.ts
- packages/front-end/src/app/pages/labs/[labId]/run-pipeline/[pipelineId].vue
- packages/front-end/src/app/pages/labs/[labId]/run-workflow/[workflowId].vue
- packages/front-end/src/app/stores/run.ts
- packages/front-end/src/app/stores/ui.ts
Add Generate Sample Sheet button
Add the generate sample sheet button when needed.
Also includes some improvements to the wip run handling in the store.
This has a lot of cases and I've checked as many of them as I can think of, but it will need thorough attention in QA.
> feat(EG-1064): generate sample sheet button

- packages/front-end/src/app/components/EGFileExplorer.vue
Adds ability to open a `.html` file from the File Explorer in a new tab.
Click action on a row will now open a the raw html in a new browser tab. Existing "Download" action on a row containing a html file remains intact.
Manually tested action in browser.
> feat(EG-1057): open html file in new tab

- packages/front-end/src/app/components/EGAddLabUsersModule.vue
- packages/front-end/src/app/stores/ui.ts
Allow selecting multiple users to add to a lab at a time
Tested with one and multiple users.
> feat(EG-1051): bulk lab invite

- packages/back-end/src/app/controllers/easy-genomics/user/create-bulk-user-invitation-requests.lambda.ts
Restrict create-bulk-user-invitation-requests API access to SysAdmin & OrgAdmins
Restrict create-bulk-user-invitation-requests API access to SysAdmin & OrgAdmins
None.
None.
> fix(EG-1074): restrict create-bulk-user-invitation-requests API access to SysAdmin & OrgAdmins

- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/components/EGTable.vue
Make EGTables apply sort through all pages as they should
Title says enough.
Ignore the first commit, it's a code grooming commit with a massive diff but no functional change.
It works :)
> fix(EG-669): lab runs sorting

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
- packages/front-end/tests/e2e/lab-technician/Labs_Lab_Technician.spec.e2e.ts
- packages/front-end/tests/e2e/org-admin/Labs_Org_Admin.spec.e2e.ts
- packages/front-end/tests/e2e/sys-admin/Organizations_System_Admin.spec.e2e.ts
Automated test to check uploading pair and single files together and fix Users and Settings tabs (eg-1047 & EG-1080)
This PR includes the following:
1. New scripts to test uploading pair and single files together that's expected to fail
2. Fix scripts relating to the updated Users and Setting tab that is failing at the moment
Ran the tests in different roles successfully
This affects 4 files:
1. Labs_Lab_Manager.spec.e2e.ts
2. Labs_Lab_Technician.spec.e2e.ts
3. Labs_Org_Admin.spec.e2e.ts
4. Organizations_System_Admin.spec.e2e.ts
none
> feat(EG-1047): test upload mixed files and rename users and settings tabs

- packages/front-end/src/app/components/EGLabView.vue
Fix a typo breaking the add users button
> fix(EG-1083): orgid misspell

- packages/front-end/src/app/components/EGRunFormUploadData.vue
Remove file upload confirmation toast
> feat(EG-1078): remove upload confirmation toast

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Update the File Manager tests to detect the correct sample sheet file name to make the tests pass
This is a minor update to change the file naming convention in the Labs_Lab_Manager.spec.e2e.ts
.getByRole('row', { name: 'samplesheet-' + seqRunNameVar + '.csv' })
Tests passed locally
Only impacts Labs_Lab_Manager.spec.e2e.ts
> fix(EG-1086): update sample sheet file naming convention

- packages/front-end/src/app/pages/admin/index.vue
Fix bug introduced in #605 causing sysadmin to log into a 404 page
> fix(EG-1089): superuser log in ending in 404

- packages/front-end/tests/e2e/lab-manager/Labs_Lab_Manager.spec.e2e.ts
Additional test to check accuracy of the sample sheet url in the purple bar in Steps 2-3 and Run Details
Added lines of code to assert the value of the url and the filenames of the samplesheet
All tests passed locally
Only affect the Labs_Lab_Manager.spec.e2e.ts
None
> feat(EG-1044): verify sample sheet url

- packages/back-end/src/app/utils/rest-api-utils.ts
- packages/front-end/src/app/components/EGLabView.vue
- packages/front-end/src/app/repository/modules/labs.ts
Improve filtering wildcard logic
- allow wildcards anywhere in filter
- allow any number of wildcards
The filter box in this video is not included in this PR. It's just for demonstration. This PR only has the filtering logic change on the BE and a transparent code improvement on the FE.
https://github.com/user-attachments/assets/e4a6d797-86c3-40b8-bd9f-9ff69137ff24
As briefly discussed, potential performance questions that we don't have time to investigate right now.
> feat(EG-1091): improved filter wildcards
